import * as DropdownMenu from '@radix-ui/react-dropdown-menu'
import { ArchiveRestore, Check, Clock3, FilePenLine, History, MoreHorizontal, Plus, Rocket, Search, Star, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { toast } from 'sonner'

import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
import { createAsk, createRelease, decideAsk, deleteAsk, deleteDraft, deleteRelease, purgeTrashEntry, recordRecentResource, restoreTrashEntry, searchWorkspace, updateRelease } from '@/lib/api'
import type { Ask, BootstrapData, Draft, Release, SearchResponse } from '@/types/flow'

import './workspace-operations.css'

export type OperationsView = 'drafts'|'releases'|'asks'|'favorites'|'recent'|'audit-log'|'deleted'

export function WorkspaceOperationsPage({ data, view, initialReleaseId, onOpenSidebar, onReload, onNavigate, onResumeDraft }: { data: BootstrapData; view: OperationsView; initialReleaseId?: string; onOpenSidebar: () => void; onReload: () => Promise<void>; onNavigate: (path: string) => void; onResumeDraft: (draft: Draft) => void }) {
  const [query, setQuery] = useState('')
  const [createOpen, setCreateOpen] = useState(false)
  const [editingRelease, setEditingRelease] = useState<Release>()
  const [askDecision, setAskDecision] = useState<{ ask: Ask; decision: 'approved'|'rejected' }>()
  const [recent, setRecent] = useState<SearchResponse['recent']>([])
  const openedRelease = useRef('')
  useEffect(() => { if (view === 'recent') void searchWorkspace('', [], 30).then(value => setRecent(value.recent)).catch(() => setRecent([])) }, [view])
  useEffect(() => {
    if (view !== 'releases' || !initialReleaseId || openedRelease.current === initialReleaseId) return
    const release = data.releases.find(item => item.id === initialReleaseId && !item.archivedAt)
    if (!release) return
    openedRelease.current = initialReleaseId
    void recordRecentResource('release', release.id)
    setEditingRelease(release)
  }, [data.releases, initialReleaseId, view])
  const title = ({ drafts: 'Drafts', releases: 'Releases', asks: 'Asks', favorites: 'Favorites', recent: 'Recently viewed', 'audit-log': 'Audit log', deleted: 'Recently deleted' } as const)[view]
  const canCreate = view === 'releases' || view === 'asks'
  return <main className="main-panel operations-page" aria-label={title}>
    <header className="operations-header">
      <button className="operations-mobile-menu" aria-label="Open sidebar" onClick={onOpenSidebar}><span/><span/><span/></button>
      <h1>{title}</h1>
      {canCreate && <button className="operations-icon-button" aria-label={`New ${view === 'asks' ? 'ask' : 'release'}`} onClick={() => setCreateOpen(true)}><Plus size={16}/></button>}
    </header>
    <div className="operations-toolbar"><label><Search size={14}/><input aria-label={`Search ${title}`} placeholder={`Search ${title.toLowerCase()}…`} value={query} onChange={event => setQuery(event.target.value)}/>{query && <button aria-label="Clear search" onClick={() => setQuery('')}><X size={12}/></button>}</label></div>
    {view === 'drafts' && <DraftRows data={data} drafts={data.drafts} query={query} onDelete={async draft => { await deleteDraft(draft.id); clearLocalIssueDraft(draft); await onReload() }} onNavigate={onNavigate} onResume={onResumeDraft}/>} 
    {view === 'releases' && <ReleaseRows releases={data.releases} query={query} onOpen={release => { void recordRecentResource('release', release.id); setEditingRelease(release) }} onDelete={async id => { await deleteRelease(id); await onReload() }}/>} 
    {view === 'asks' && <AskRows asks={data.asks} query={query} onDecide={(ask, decision) => setAskDecision({ ask, decision })} onDelete={async id => { await deleteAsk(id); await onReload() }}/>} 
    {view === 'favorites' && <FavoriteRows data={data} query={query} onNavigate={onNavigate}/>} 
    {view === 'recent' && <RecentRows data={data} recent={recent} query={query} onNavigate={onNavigate}/>} 
    {view === 'audit-log' && <AuditRows data={data} query={query}/>} 
    {view === 'deleted' && <TrashRows data={data} query={query} onRestore={async id => { await restoreTrashEntry(id); await onReload() }} onPurge={async id => { await purgeTrashEntry(id); await onReload() }}/>} 
    {createOpen && <CreateOperationDialog view={view as 'releases'|'asks'} data={data} onClose={() => setCreateOpen(false)} onCreated={async () => { setCreateOpen(false); await onReload() }}/>} 
    {editingRelease && <CreateOperationDialog view="releases" data={data} release={editingRelease} onClose={() => setEditingRelease(undefined)} onCreated={async () => { setEditingRelease(undefined); await onReload() }}/>} 
    {askDecision && <AskDecisionDialog value={askDecision} onClose={() => setAskDecision(undefined)} onSubmit={async note => { await decideAsk(askDecision.ask.id, askDecision.decision, note); setAskDecision(undefined); await onReload() }}/>} 
  </main>
}

function Empty({ icon, title, body }: { icon: ReactNode; title: string; body: string }) { return <div className="operations-empty">{icon}<strong>{title}</strong><span>{body}</span></div> }
function matches(query: string, ...values: (string|undefined)[]) { const needle = query.trim().toLowerCase(); return !needle || values.some(value => value?.toLowerCase().includes(needle)) }
function RowMenu({ children }: { children: ReactNode }) { return <DropdownMenu.Root><DropdownMenu.Trigger asChild><button className="operations-row-menu" aria-label="Open actions"><MoreHorizontal size={15}/></button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="operations-menu" align="end" sideOffset={5}>{children}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root> }
function MenuItem({ icon, children, onSelect, danger }: { icon: ReactNode; children: ReactNode; onSelect: () => void; danger?: boolean }) { return <DropdownMenu.Item className={danger ? 'danger' : ''} onSelect={onSelect}>{icon}<span>{children}</span></DropdownMenu.Item> }
function relative(value: string) { const delta = Date.now() - new Date(value).getTime(); const minutes = Math.max(0, Math.floor(delta/60000)); if (minutes < 60) return `${minutes || 1}m`; const hours = Math.floor(minutes/60); if (hours < 24) return `${hours}h`; return `${Math.floor(hours/24)}d` }

function DraftRows({ data, drafts, query, onDelete, onNavigate, onResume }: { data: BootstrapData; drafts: Draft[]; query: string; onDelete: (draft: Draft) => Promise<void>; onNavigate: (path: string) => void; onResume: (draft: Draft) => void }) {
  const rows = drafts.filter(item => matches(query, item.title, item.body, item.type))
  if (!rows.length) return <Empty icon={<FilePenLine/>} title="No active drafts" body="Unfinished issues, comments, and documents appear here automatically."/>
  return <div className="operations-list">{rows.map(item => <div className="operations-row" key={item.id}><span className="operations-glyph"><FilePenLine/></span><button className="operations-row-main" onClick={() => item.type === 'issue' && !item.resourceId ? onResume(item) : item.resourceId && resourcePath(data,item.type,item.resourceId) ? onNavigate(resourcePath(data,item.type,item.resourceId)) : toast.info('Open the matching composer to continue this draft')}><strong>{item.title || 'Untitled draft'}</strong><small>{item.type} · Edited {relative(item.updatedAt)} ago</small></button><RowMenu><MenuItem icon={<Trash2/>} danger onSelect={() => void onDelete(item)}>Delete draft</MenuItem></RowMenu></div>)}</div>
}

function clearLocalIssueDraft(draft: Draft) {
  if (draft.type !== 'issue') return
  const teamId = typeof draft.metadata?.teamId === 'string' ? draft.metadata.teamId : ''
  if (!teamId) return
  try { localStorage.removeItem(`flow:create-issue-draft:${teamId}`) } catch { /* Storage cleanup is best-effort. */ }
}

function ReleaseRows({ releases, query, onDelete, onOpen }: { releases: Release[]; query: string; onDelete: (id: string) => Promise<void>; onOpen: (release: Release) => void }) {
  const rows = releases.filter(item => !item.archivedAt && matches(query, item.name, item.version, item.description))
  if (!rows.length) return <Empty icon={<Rocket/>} title="No releases" body="Create a release to group the projects and issues that ship together."/>
  return <div className="operations-list">{rows.map(item => <div className="operations-row" key={item.id}><span className={`operations-status ${item.status}`}/><button className="operations-row-main" onClick={() => onOpen(item)}><strong>{item.name}{item.version && <em>{item.version}</em>}</strong><small>{item.projectIds.length} projects · {item.issueIds.length} issues{item.targetDate ? ` · ${item.targetDate}` : ''}</small></button><span className="operations-state">{item.status === 'inProgress' ? 'In progress' : item.status}</span><RowMenu><MenuItem icon={<Trash2/>} danger onSelect={() => void onDelete(item.id)}>Delete release</MenuItem></RowMenu></div>)}</div>
}

function AskRows({ asks, query, onDecide, onDelete }: { asks: Ask[]; query: string; onDecide: (ask: Ask, decision: 'approved'|'rejected') => void; onDelete: (id: string) => Promise<void> }) {
  const rows = asks.filter(item => matches(query, item.title, item.body, item.source))
  if (!rows.length) return <Empty icon={<Clock3/>} title="No asks" body="Requests submitted from web, Slack, or email will wait here for review."/>
  return <div className="operations-list">{rows.map(item => <div className="operations-row" key={item.id}><span className={`operations-ask-status ${item.status}`}>{item.status === 'pending' ? <Clock3/> : <Check/>}</span><div className="operations-row-main"><strong>{item.title}</strong><small>{item.requester.displayName} · {item.source} · {relative(item.createdAt)} ago</small></div><span className="operations-state">{item.status}</span><RowMenu>{item.status === 'pending' && <><MenuItem icon={<Check/>} onSelect={() => onDecide(item, 'approved')}>Approve...</MenuItem><MenuItem icon={<X/>} onSelect={() => onDecide(item, 'rejected')}>Reject...</MenuItem><DropdownMenu.Separator/></>}<MenuItem icon={<Trash2/>} danger onSelect={() => void onDelete(item.id)}>Delete ask</MenuItem></RowMenu></div>)}</div>
}

function resourceLabel(data: BootstrapData, type: string, id: string) { if (type === 'issue') return data.issues.find(x => x.id === id)?.title; if (type === 'project') return data.projects.find(x => x.id === id)?.name; if (type === 'document') return data.documents.find(x => x.id === id)?.title; if (type === 'release') return data.releases.find(x => x.id === id)?.name; if (type === 'customer') return data.customers.find(x => x.id === id)?.name; if (type === 'initiative') return data.initiatives.find(x => x.id === id)?.name; if (type === 'view') return data.savedViews.find(x => x.id === id)?.name; return undefined }
function resourcePath(data: BootstrapData, type: string, id: string) { if (type === 'issue') { const value=data.issues.find(x=>x.id===id); return value ? `/${data.workspace.urlKey}/issue/${value.identifier}` : '' } if (type === 'project') { const value=data.projects.find(x=>x.id===id); return value ? `/${data.workspace.urlKey}/project/${value.slugId}/overview` : '' } if (type === 'document') { const value=data.documents.find(x=>x.id===id); return value ? `/${data.workspace.urlKey}/document/${value.slugId}` : '' } if(type==='initiative'){const value=data.initiatives.find(x=>x.id===id);return value?`/${data.workspace.urlKey}/initiative/${value.slugId}/overview`:''} if(type==='customer'){const value=data.customers.find(x=>x.id===id);return value?`/${data.workspace.urlKey}/customer/${operationSlug(value.name)}-${value.id.slice(-12)}`:''} if(type==='release')return `/${data.workspace.urlKey}/releases?release=${encodeURIComponent(id)}`; if(type==='view'){const value=data.savedViews.find(x=>x.id===id);if(!value)return '';const team=value.scope==='team'?data.teams.find(x=>x.id===value.teamId):undefined;const root=`/${data.workspace.urlKey}`;if((value.resource??'issues')==='projects')return team?`${root}/team/${team.key}/projects/view/${encodeURIComponent(id)}`:`${root}/projects/view/${encodeURIComponent(id)}`;return team?`${root}/team/${team.key}/view/${encodeURIComponent(id)}`:`${root}/view/${encodeURIComponent(id)}`} return '' }
function operationSlug(value:string){return value.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'').slice(0,80)||'item'}
function FavoriteRows({ data, query, onNavigate }: { data: BootstrapData; query: string; onNavigate: (path: string) => void }) { const rows = data.favorites.map(item => ({...item,label:resourceLabel(data,item.resourceType,item.resourceId)})).filter(item => item.label && matches(query,item.label,item.resourceType)); if (!rows.length) return <Empty icon={<Star/>} title="No favorites" body="Favorite an issue, project, document, customer, or view to find it here."/>; return <div className="operations-list">{rows.map(item => <button className="operations-row" key={item.id} onClick={() => { const path=resourcePath(data,item.resourceType,item.resourceId); if(path)onNavigate(path) }}><span className="operations-glyph"><Star/></span><span className="operations-row-main"><strong>{item.label}</strong><small>{item.resourceType}</small></span></button>)}</div> }
function RecentRows({ data, recent, query, onNavigate }: { data: BootstrapData; recent: SearchResponse['recent']; query: string; onNavigate: (path: string) => void }) { const rows=recent.map(item=>({...item,label:resourceLabel(data,item.resourceType,item.resourceId)})).filter(item=>item.label&&matches(query,item.label,item.resourceType)); if(!rows.length)return <Empty icon={<History/>} title="No recent items" body="Resources you open across the workspace will appear here."/>; return <div className="operations-list">{rows.map(item=><button className="operations-row" key={`${item.resourceType}:${item.resourceId}`} onClick={()=>{const path=resourcePath(data,item.resourceType,item.resourceId);if(path)onNavigate(path)}}><span className="operations-glyph"><History/></span><span className="operations-row-main"><strong>{item.label}</strong><small>{item.resourceType} · {relative(item.lastViewedAt)} ago</small></span></button>)}</div> }
function AuditRows({ data, query }: { data: BootstrapData; query: string }) { const rows=data.auditLog.filter(item=>matches(query,item.action,item.resourceType,item.actor.displayName)); if(!rows.length)return <Empty icon={<History/>} title="No audit events" body="Administrative and data lifecycle actions will appear here."/>; return <div className="operations-list">{rows.map(item=><div className="operations-row" key={item.id}><span className="operations-avatar">{item.actor.displayName.slice(0,2).toUpperCase()}</span><span className="operations-row-main"><strong>{item.actor.displayName} <b>{item.action.replaceAll('_',' ')}</b> {item.resourceType.replaceAll('_',' ')}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></span><code>{item.resourceId}</code></div>)}</div> }
function TrashRows({ data, query, onRestore, onPurge }: { data: BootstrapData; query: string; onRestore: (id: string) => Promise<void>; onPurge: (id: string) => Promise<void> }) { const rows=data.trash.filter(item=>matches(query,item.title,item.resourceType)); if(!rows.length)return <Empty icon={<Trash2/>} title="Recently deleted is empty" body="Deleted content remains recoverable for 30 days."/>; return <div className="operations-list">{rows.map(item=><div className="operations-row" key={item.id}><span className="operations-glyph"><Trash2/></span><span className="operations-row-main"><strong>{item.title}</strong><small>{item.resourceType.replaceAll('_',' ')} · Deleted {relative(item.deletedAt)} ago · Expires {new Date(item.expiresAt).toLocaleDateString()}</small></span><RowMenu><MenuItem icon={<ArchiveRestore/>} onSelect={()=>void onRestore(item.id)}>Restore</MenuItem><DropdownMenu.Separator/><MenuItem icon={<Trash2/>} danger onSelect={()=>void onPurge(item.id)}>Delete permanently</MenuItem></RowMenu></div>)}</div> }

function AskDecisionDialog({ value, onClose, onSubmit }: { value: { ask: Ask; decision: 'approved'|'rejected' }; onClose: () => void; onSubmit: (note: string) => Promise<void> }) {
  const [note,setNote]=useState('')
  const [saving,setSaving]=useState(false)
  const approve=value.decision==='approved'
  const submit=async()=>{setSaving(true);try{await onSubmit(note.trim())}catch(error){toast.error(error instanceof Error?error.message:'Could not update ask')}finally{setSaving(false)}}
  return <Dialog open onOpenChange={open=>!open&&!saving&&onClose()}><DialogContent className="operations-dialog operations-decision-dialog"><DialogTitle>{approve?'Approve ask':'Reject ask'}</DialogTitle><div className="operations-decision-summary"><span className={`operations-ask-status ${value.ask.status}`}><Clock3/></span><div><strong>{value.ask.title}</strong><small>{value.ask.requester.displayName} · {value.ask.source}</small></div></div><label><span>Decision note <small>(optional)</small></span><textarea autoFocus value={note} onChange={event=>setNote(event.target.value)} placeholder={approve?'Add context for the created issue…':'Explain why this request was rejected…'}/></label><footer><button disabled={saving} onClick={onClose}>Cancel</button><button className={approve?'primary':'danger'} disabled={saving} onClick={()=>void submit()}>{saving?'Saving…':approve?'Approve and create issue':'Reject ask'}</button></footer></DialogContent></Dialog>
}

function CreateOperationDialog({ view, data, release, onClose, onCreated }: { view: 'releases'|'asks'; data: BootstrapData; release?: Release; onClose: () => void; onCreated: () => Promise<void> }) {
  const [name,setName]=useState(release?.name??''); const [description,setDescription]=useState(release?.description??''); const [saving,setSaving]=useState(false); const [teamId,setTeamId]=useState(data.teams[0]?.id??'')
  const [templateId,setTemplateId]=useState('')
  const [version,setVersion]=useState(release?.version??''); const [status,setStatus]=useState<Release['status']>(release?.status??'planned'); const [targetDate,setTargetDate]=useState(release?.targetDate??'')
  const [projectIds,setProjectIds]=useState<string[]>(release?.projectIds??[]); const [issueIds,setIssueIds]=useState<string[]>(release?.issueIds??[])
  const toggle=(values:string[],id:string,setter:(next:string[])=>void)=>setter(values.includes(id)?values.filter(value=>value!==id):[...values,id])
  const templates=data.issueTemplates.filter(item=>item.teamId===teamId)
  const submit=async()=>{setSaving(true);try{if(view==='releases'){const input={name,description,version,status,targetDate,projectIds,issueIds};if(release)await updateRelease(release.id,input);else await createRelease(input)}else await createAsk({title:name,body:description,teamId,templateId:templateId||undefined});await onCreated()}catch(error){toast.error(error instanceof Error?error.message:'Could not save')}finally{setSaving(false)}}
  return <Dialog open onOpenChange={open=>!open&&onClose()}><DialogContent className="operations-dialog"><DialogTitle>{view==='releases'?(release?'Edit release':'Create release'):'Create ask'}</DialogTitle><label><span>{view==='releases'?'Release name':'Request title'}</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={view==='releases'?'Summer release':'What do you need?'}/></label>{view==='releases'&&<div className="operations-dialog-fields"><label><span>Version</span><input value={version} onChange={event=>setVersion(event.target.value)} placeholder="v1.0"/></label><label><span>Status</span><select value={status} onChange={event=>setStatus(event.target.value as Release['status'])}><option value="planned">Planned</option><option value="inProgress">In progress</option><option value="released">Released</option><option value="canceled">Canceled</option></select></label><label><span>Target date</span><input type="date" value={targetDate} onChange={event=>setTargetDate(event.target.value)}/></label></div>}{view==='asks'&&<div className="operations-dialog-fields"><label><span>Team</span><select value={teamId} onChange={e=>{setTeamId(e.target.value);setTemplateId('')}}>{data.teams.map(team=><option value={team.id} key={team.id}>{team.name}</option>)}</select></label><label><span>Issue template</span><select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">No template</option>{templates.map(template=><option value={template.id} key={template.id}>{template.name}</option>)}</select></label></div>}<label><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Add details…"/></label>{view==='releases'&&<div className="operations-associations"><fieldset><legend>Projects</legend>{data.projects.length?data.projects.map(project=><label key={project.id}><input type="checkbox" checked={projectIds.includes(project.id)} onChange={()=>toggle(projectIds,project.id,setProjectIds)}/><i style={{background:project.color}}/><span>{project.name}</span></label>):<small>No projects</small>}</fieldset><fieldset><legend>Issues</legend>{data.issues.length?data.issues.slice(0,100).map(issue=><label key={issue.id}><input type="checkbox" checked={issueIds.includes(issue.id)} onChange={()=>toggle(issueIds,issue.id,setIssueIds)}/><span><b>{issue.identifier}</b>{issue.title}</span></label>):<small>No issues</small>}</fieldset></div>}<footer><button onClick={onClose}>Cancel</button><button className="primary" disabled={!name.trim()||saving} onClick={()=>void submit()}>{saving?'Saving…':release?'Save changes':'Create'}</button></footer></DialogContent></Dialog>
}
