import { Check, ChevronDown, ChevronRight, ExternalLink, FileText, GitPullRequest, Link2, Plus, UserRound, X } from 'lucide-react'
import * as Popover from '@radix-ui/react-popover'
import * as Select from '@radix-ui/react-select'
import * as Dialog from '@radix-ui/react-dialog'
import type { ActivityEvent, Attachment, BootstrapData, CodeReview, Comment, FlowDocument, Issue, IssueRelationType, IssueUpdateInput, Presence, Project, ProjectMilestone } from '@/types/flow'
import { Button } from '@/components/ui/button'
import { IssueDescriptionEditor } from '@/components/issue/issue-description-editor'
import { ActivityTimeline } from '@/components/activity/activity-timeline'
import { Composer } from '@/components/editor/composer'
import { Avatar } from '@/components/issue/issue-row'
import { AddReactionIcon, AttachmentIcon, StatusIcon } from '@/components/issue/issue-icons'
import { SubIssueEditor } from '@/components/issue/sub-issue-editor'
import { RelationPicker } from '@/components/issue/relation-picker'
import { IssueHeader } from '@/components/issue/issue-header'
import { IssueTitleEditor } from '@/components/issue/issue-title-editor'
import { AssigneePicker, PriorityPicker, StatusPicker } from '@/components/issue/core-property-pickers'
import { CyclePicker, EstimatePicker, LabelPicker } from '@/components/issue/label-project-pickers'
import { IssueProjectPicker } from '@/components/issue/issue-project-picker'
import type { NewProjectDraft } from '@/components/projects-page/new-project-dialog'
import { IssueAttachments, type AttachmentUploadState } from '@/components/issue/issue-attachments'
import { DueDatePicker } from '@/components/issue/due-date-picker'
import { IssueReleasePicker } from '@/components/issue/issue-release-picker'
import { IssueSubscriberPicker } from '@/components/issue/issue-subscriber-picker'
import { useEffect, useRef, useState } from 'react'
import { useIssueAutosave } from '@/components/issue/editor/use-issue-autosave'
import { EmojiPicker, ReactionPills } from '@/components/reactions/emoji-picker'
import type { SubIssueInput } from '@/components/issue/sub-issue-editor'
import { IssueSLAIndicator } from '@/components/issue/issue-sla-indicator'
import type { IssueOptionsActions } from '@/components/issue/issue-options-menu'
import { documentPath } from '@/lib/app-routes'
import { labelsForResource, toggleGroupedLabelIds } from '@/lib/labels'
import { useI18n } from '@/i18n/i18n'
import { Toggle } from '@/components/ui/toggle'
import { DisplayIcon } from '@/components/ui/view-action-icons'
import { SubIssueProgressRing } from '@/components/issue/sub-issue-progress-ring'
import { CheckboxMark } from '@/components/ui/checkbox-mark'
import './issue-code-reviews.css'

export function DetailPane({issue,data,comments,activities,presence=[],full=false,embedded=false,issueOptionsActions,onClose,onNavigateIssue,onNavigateRoot,onUpdate,onDelete,onCreateSubIssue,onCreateProject,onCreateProjectMilestone,onReactIssue,onComment,onEditComment,onDeleteComment,onReactComment,onRelation,onDeleteRelation,onUpload,onDeleteAttachment}:{issue:Issue;data:BootstrapData;comments:Comment[];activities:ActivityEvent[];presence?:Presence[];full?:boolean;embedded?:boolean;issueOptionsActions?:IssueOptionsActions;onClose:()=>void;onExpand?:()=>void;onNavigateIssue?:(issue:Issue)=>void;onNavigateRoot?:()=>void;onUpdate:(input:IssueUpdateInput)=>Promise<void>;onDelete:()=>Promise<void>;onCreateSubIssue:(input:SubIssueInput)=>Promise<void>;onCreateProject?:(draft:NewProjectDraft)=>Promise<Project>;onCreateProjectMilestone?:(projectId:string,input:{name:string})=>Promise<ProjectMilestone>;onReactIssue:(emoji:string)=>Promise<void>;onComment:(body:string,bodyData?:Record<string,unknown>,parentId?:string)=>Promise<void>;onEditComment:(id:string,body:string,bodyData?:Record<string,unknown>)=>Promise<void>;onDeleteComment:(id:string)=>Promise<void>;onReactComment:(id:string,emoji:string)=>Promise<void>;onRelation:(type:IssueRelationType,relatedIssueId:string)=>Promise<void>;onDeleteRelation:(relationId:string)=>Promise<void>;onUpload:(file:File)=>Promise<void>;onDeleteAttachment:(attachmentId:string)=>Promise<void>}){
  const{t}=useI18n(),[title,setTitle]=useState(issue.title),[description,setDescription]=useState(issue.description),[subOpen,setSubOpen]=useState(false),[subCollapsed,setSubCollapsed]=useState(false),[subSelected,setSubSelected]=useState(new Set<string>()),[subDisplay,setSubDisplay]=useState<SubIssueDisplay>({ordering:'priority',direction:'asc',completed:'all',nested:true,properties:new Set(['status','labels','assignee'])}),[relationType,setRelationType]=useState<IssueRelationType|null>(null),[uploadState,setUploadState]=useState<AttachmentUploadState>()
  const fileRef=useRef<HTMLInputElement>(null)
  const {state:saveState,schedule,flush,retry}=useIssueAutosave(onUpdate)
  useEffect(()=>{setTitle(issue.title);setDescription(issue.description)},[issue.id,issue.title,issue.description])
  const subIssues=flattenSubIssues(issue,data.issues,subDisplay.nested).filter(({issue:child})=>subDisplay.completed==='all'||(child.state.type!=='completed'&&child.state.type!=='canceled')).sort((a,b)=>(subDisplay.ordering==='created'?b.issue.createdAt.localeCompare(a.issue.createdAt):subDisplay.ordering==='updated'?b.issue.updatedAt.localeCompare(a.issue.updatedAt):a.issue.priority-b.issue.priority||a.issue.sortOrder-b.issue.sortOrder)*(subDisplay.direction==='asc'?1:-1))
  const subCompleted=subIssues.filter(({issue:child})=>child.state.type==='completed'||child.state.type==='canceled').length
  const sequence=data.issues.filter(item=>!item.archivedAt)
  const sequenceIndex=Math.max(0,sequence.findIndex(item=>item.id===issue.id))
  const navigateIssue=(direction:'next'|'previous')=>{const next=sequence[sequenceIndex+(direction==='next'?1:-1)];if(next)onNavigateIssue?.(next)}
  const openIssue=(target:Issue)=>{void flush().then(saved=>{if(saved)onNavigateIssue?.(target)})}
  const related=(id:string)=>data.issues.find(i=>i.id===id)
  const parentIssue=issue.parentId?related(issue.parentId):undefined
  const availableStates=statesForIssue(data,issue)
  const availableLabels=labelsForResource(data.labels,'issue',data.labelGroups).filter(label=>!label.scope||label.scope==='Workspace'||label.scope===issue.team.id)
  const linkedDocuments=data.documents.filter(document=>document.issueId===issue.id&&!document.archivedAt)
  const linkedResources=issue.attachments.filter(attachment=>attachment.contentType==='text/uri-list')
  const fileAttachments=issue.attachments.filter(attachment=>attachment.contentType!=='text/uri-list')
  const customerRequests=data.customerRequests.filter(request=>request.issueId===issue.id)
  const linkedReviews=data.reviews.filter(review=>review.issueIds.includes(issue.id))
  const releasesEnabled=data.workspaceSettings.featureFlags.releases??true
  const estimateType=data.teamSettings[issue.team.id]?.estimateType??'notUsed'
  const toggleLabel=async(id:string)=>{await onUpdate({labelIds:toggleGroupedLabelIds(issue.labels.map(x=>x.id),id,availableLabels)})}
  const toggleSubscriber=async(id:string)=>onUpdate({subscriberIds:issue.subscriberIds.includes(id)?issue.subscriberIds.filter(x=>x!==id):[...issue.subscriberIds,id]})
  const upload=async(file:File)=>{setUploadState({name:file.name,progress:20,file});try{setUploadState({name:file.name,progress:70,file});await onUpload(file);setUploadState(undefined)}catch(error){setUploadState({name:file.name,progress:100,file,error:error instanceof Error?error.message:'Upload failed'})}}
  return <section className={`issue-view ${full?'full':''} ${embedded?'issue-view--embedded':''}`}>
    {!embedded&&<IssueHeader
      issue={issue} states={availableStates} presence={presence} saveState={saveState} data={data} activities={activities} issueOptionsActions={issueOptionsActions}
      onRetrySave={()=>void retry()} position={sequenceIndex+1} total={sequence.length}
      onClose={()=>{void flush().then(saved=>{if(saved)onClose()})}}
      onNavigate={direction=>{void flush().then(saved=>{if(saved)navigateIssue(direction)})}}
      onNavigateIssue={openIssue} onNavigateRoot={onNavigateRoot?()=>{void flush().then(saved=>{if(saved)onNavigateRoot()})}:undefined}
      onUpdate={onUpdate} onDelete={onDelete} onRelation={setRelationType}
    />}
    <div className="issue-scroll"><div className="issue-layout">
      <article className="issue-document">
        <IssueTitleEditor value={title} onChange={value=>{setTitle(value);schedule({title:value})}} onBlur={()=>void flush()}/>
        {parentIssue&&<IssueParentContext parent={parentIssue} issues={data.issues} workspaceKey={data.workspace.urlKey} onOpen={()=>openIssue(parentIssue)}/>}
        <div className="issue-mobile-properties" aria-label="Issue properties">
          <StatusPicker value={issue.state} states={availableStates} onChange={stateId=>onUpdate({stateId})}/><PriorityPicker value={issue.priority} onChange={priority=>onUpdate({priority})}/>{estimateType!=='notUsed'&&<EstimatePicker value={issue.estimate} estimateType={estimateType} onChange={estimate=>onUpdate({estimate})}/>}<AssigneePicker value={issue.assignee} users={data.users} onChange={assigneeId=>onUpdate({assigneeId})}/><CyclePicker valueId={issue.cycleId} cycles={data.cycles} issues={data.issues} teamId={issue.team.id} onChange={cycleId=>onUpdate({cycleId})}/><LabelPicker value={issue.labels} labels={availableLabels} labelGroups={data.labelGroups} onToggle={toggleLabel}/><IssueProjectPicker data={data} issue={issue} onCreateMilestone={onCreateProjectMilestone} onCreateProject={onCreateProject} onUpdate={onUpdate}/>{releasesEnabled&&<IssueReleasePicker data={data} issue={issue}/>}
        </div>
        <IssueDescriptionEditor
          value={description}
          state={issue.documentContent?.contentData?JSON.stringify(issue.documentContent.contentData):issue.descriptionState}
          onBlur={()=>void flush()}
          onChange={snapshot=>setDescription(snapshot.markdown)}
          collaboration={{
            workspaceKey:data.workspace.urlKey,
            issueId:issue.id,
            documentId:issue.documentContent?.id??`document_content_${issue.id}`,
            contentState:issue.documentContent?.contentState,
            viewer:data.viewer,
            onPersist:(snapshot,updateIds)=>onUpdate({description:snapshot.markdown,descriptionState:snapshot.documentJSON,descriptionData:snapshot.document as Record<string,unknown>,contentState:snapshot.contentState,documentUpdateIds:updateIds,expectedDocumentVersion:issue.documentContent?.version??0}),
          }}
        />
        <div className="document-actions"><EmojiPicker onSelect={onReactIssue}><Button className="issue-document-action" variant="ghost" aria-label="Add reaction"><AddReactionIcon/></Button></EmojiPicker><Button className="issue-document-action" variant="ghost" aria-label="Attach images, files, or videos" onClick={()=>fileRef.current?.click()}><AttachmentIcon/></Button>{subIssues.length===0&&<Button className="issue-empty-sub-issue-action" variant="ghost" aria-label="Create new sub-issue" onClick={()=>setSubOpen(true)}><Plus size={16}/>Add sub-issues</Button>}<input ref={fileRef} type="file" multiple hidden onChange={e=>{for(const file of Array.from(e.target.files??[]))void upload(file);e.target.value='' }}/></div>
        <ReactionPills reactions={issue.reactions} viewerId={data.viewer.id} onToggle={onReactIssue}/>
        {subOpen&&<SubIssueEditor parent={issue} data={data} onCancel={()=>setSubOpen(false)} onCreate={async input=>{await onCreateSubIssue(input);setSubOpen(false)}}/>}
        {subIssues.length>0&&<section className="issue-detail-section flow-sub-issues"><header><button className="sub-issues-collapse" aria-label={t(subCollapsed?'Expand sub-issues section':'Collapse sub-issues section')} aria-expanded={!subCollapsed} onClick={()=>setSubCollapsed(value=>!value)}><ChevronDown/><span>{t('Sub-issues')}</span></button><span className="sub-issues-progress"><SubIssueProgressRing completed={subCompleted} total={subIssues.length}/><span>{subCompleted}/{subIssues.length}</span></span><span/><SubIssueDisplayMenu value={subDisplay} onChange={setSubDisplay}/><button className="sub-issues-create" aria-label={t('Create new sub-issue')} onClick={()=>setSubOpen(true)}><Plus/></button></header>{!subCollapsed&&<div className="sub-issues-list">{subIssues.map(({issue:child,depth})=><DetailSubIssueRow child={child} data={data} depth={depth} key={child.id} selected={subSelected.has(child.id)} properties={subDisplay.properties} onOpen={()=>openIssue(child)} onSelect={()=>setSubSelected(current=>{const next=new Set(current);if(next.has(child.id))next.delete(child.id);else next.add(child.id);return next})}/>)}</div>}</section>}
        {issue.relations.length>0&&<IssueSection title="Relations" count={issue.relations.length}>{issue.relations.map(relation=>{const target=related(relation.relatedIssueId);return <div className="linked-issue relation-row" key={relation.id}><Link2 size={14}/><span>{relationLabel(relation.type)}</span><strong>{target?.identifier} {target?.title}</strong><button aria-label="Remove relation" onClick={()=>onDeleteRelation(relation.id)}><X size={12}/></button></div>})}</IssueSection>}
        {linkedReviews.length>0&&<IssueCodeReviews actions={issueOptionsActions} reviews={linkedReviews}/>}
        {(linkedDocuments.length>0||linkedResources.length>0)&&<IssueResources documents={linkedDocuments} links={linkedResources} workspaceKey={data.workspace.urlKey} actions={issueOptionsActions} onDeleteLink={onDeleteAttachment}/>}
        {customerRequests.length>0&&<IssueSection title="Customer requests" count={customerRequests.length}>{customerRequests.map(request=>{const customer=data.customers.find(item=>item.id===request.customerId);return <div className="linked-issue issue-resource-row" key={request.id}><UserRound size={14}/><span>{customer?.name??'Customer'}</span><strong>{request.body}</strong></div>})}</IssueSection>}
        <IssueAttachments attachments={fileAttachments} upload={uploadState} onRetry={upload} onDelete={onDeleteAttachment}/>
        <div className="activity-heading"><span>Activity</span><div><Button className="issue-subscribe-toggle" variant="ghost" size="sm" disabled={Boolean(issue.archivedAt)} onClick={()=>toggleSubscriber(data.viewer.id)}>{issue.subscriberIds.includes(data.viewer.id)?'Unsubscribe':'Subscribe'}</Button><IssueSubscriberPicker issue={issue} users={data.users} onToggle={toggleSubscriber}/></div></div>
        <ActivityTimeline events={activities} comments={comments} viewerId={data.viewer.id} onReply={(body,bodyData,parentId)=>onComment(body,bodyData,parentId)} onEdit={onEditComment} onDelete={onDeleteComment} onReaction={onReactComment} onAttach={()=>fileRef.current?.click()}/><Composer onSubmit={onComment} onAttach={()=>fileRef.current?.click()}/>
      </article>
      <IssueProperties issue={issue} data={data} activities={activities} releasesEnabled={releasesEnabled} onCreateMilestone={onCreateProjectMilestone} onCreateProject={onCreateProject} onUpdate={onUpdate} onToggleLabel={toggleLabel}/>
    </div></div>
    {relationType&&<RelationPicker open onOpenChange={open=>!open&&setRelationType(null)} type={relationType} issueId={issue.id} issues={data.issues} onSelect={id=>onRelation(relationType,id)}/>}
  </section>
}

function IssueCodeReviews({actions,reviews}:{actions?:IssueOptionsActions;reviews:CodeReview[]}){
  const[collapsed,setCollapsed]=useState(false)
  return <section className="issue-detail-section issue-code-reviews"><header><button aria-expanded={!collapsed} aria-label={collapsed?'Expand pull requests section':'Collapse pull requests section'} onClick={()=>setCollapsed(value=>!value)} type="button"><ChevronDown/><span>Pull requests</span></button><span>{reviews.length}</span></header>{!collapsed&&reviews.map(review=><a className="issue-code-review" href={review.url} key={review.id} rel="noreferrer" target="_blank"><GitPullRequest/><span><strong data-i18n-ignore>{review.title}</strong><small data-i18n-ignore>{review.repositoryOwner}/{review.repositoryName} · #{review.number}</small></span><em data-status={review.status}>{review.status==='inReview'?'In review':review.status[0].toUpperCase()+review.status.slice(1)}</em><ExternalLink className="issue-code-review__external"/><button aria-label={`Unlink pull request ${review.title}`} disabled={!actions} onClick={event=>{event.preventDefault();event.stopPropagation();void actions?.unlinkReview(review.id)}} type="button"><X/></button></a>)}</section>
}

type SubIssueProperty='priority'|'sla'|'id'|'status'|'labels'|'milestone'|'cycle'|'dueDate'|'links'|'customers'|'customerRevenue'|'assignee'
type SubIssueDisplay={ordering:'priority'|'created'|'updated';direction:'asc'|'desc';completed:'all'|'none';nested:boolean;properties:Set<SubIssueProperty>}

function flattenSubIssues(parent:Issue,issues:Issue[],nested:boolean){const byId=new Map(issues.map(item=>[item.id,item])),seen=new Set<string>();const result:{issue:Issue;depth:number}[]=[];const visit=(id:string,depth:number)=>{if(seen.has(id))return;seen.add(id);const child=byId.get(id);if(!child||child.archivedAt)return;result.push({issue:child,depth});if(nested)child.subIssueIds.forEach(childId=>visit(childId,depth+1))};parent.subIssueIds.forEach(id=>visit(id,0));return result}

function DetailSubIssueRow({child,data,depth,properties,selected,onOpen,onSelect}:{child:Issue;data:BootstrapData;depth:number;properties:Set<SubIssueProperty>;selected:boolean;onOpen:()=>void;onSelect:()=>void}){
  const labels=child.labels.slice(0,3),cycle=data.cycles.find(item=>item.id===child.cycleId),project=data.projects.find(item=>item.id===child.project?.id),milestone=(project?.milestones??[]).find(item=>item.id===child.projectMilestoneId),sla=data.issueSlas.find(item=>item.issueId===child.id&&item.status!=='removed'),rule=sla?data.slaRules.find(item=>item.id===sla.ruleId):undefined,requests=data.customerRequests.filter(item=>item.issueId===child.id),customers=requests.map(item=>data.customers.find(customer=>customer.id===item.customerId)).filter((customer):customer is NonNullable<typeof customer>=>Boolean(customer)),revenue=customers.reduce((total,customer)=>total+(customer.annualRevenue??0),0),hasStatus=properties.has('status')
  return <a className="detail-sub-issue-row" data-selected={selected} data-depth={depth} data-has-status={hasStatus} style={{'--sub-depth':depth} as React.CSSProperties} href={`/${data.workspace.urlKey}/issue/${child.identifier}`} onClick={event=>{if((event.target as Element).closest('button,[role=checkbox]')){event.preventDefault();return}event.preventDefault();onOpen()}}><span className="detail-sub-checkbox" role="checkbox" tabIndex={0} aria-label="Select issue" aria-checked={selected} onClick={event=>{event.preventDefault();event.stopPropagation();onSelect()}} onKeyDown={event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();onSelect()}}}>{selected&&<CheckboxMark/>}</span>{hasStatus&&<StatusIcon state={child.state} size={14}/>}<span className="detail-sub-title" data-i18n-ignore>{properties.has('id')&&<small>{child.identifier}</small>}{child.title}</span><span className="detail-sub-properties">{properties.has('priority')&&child.priority>0&&<span className="detail-sub-priority">{child.priorityLabel}</span>}{properties.has('sla')&&sla&&<IssueSLAIndicator compact sla={sla} ruleName={rule?.name}/>} {properties.has('labels')&&labels.map(label=><span className="detail-sub-badge" key={label.id}><i style={{background:label.color}}/><b data-i18n-ignore>{label.name}</b></span>)}{properties.has('milestone')&&milestone&&<span className="detail-sub-badge"><b data-i18n-ignore>{milestone.name}</b></span>}{properties.has('cycle')&&cycle&&<span className="detail-sub-badge"><b data-i18n-ignore>{cycle.name}</b></span>}{properties.has('dueDate')&&child.dueDate&&<span className="detail-sub-badge"><b>{child.dueDate.slice(5)}</b></span>}{properties.has('links')&&child.attachments.length>0&&<span className="detail-sub-badge"><Link2/><b>{child.attachments.length}</b></span>}{properties.has('customers')&&customers.map(customer=><span className="detail-sub-badge" key={customer.id}><b data-i18n-ignore>{customer.name}</b></span>)}{properties.has('customerRevenue')&&revenue>0&&<span className="detail-sub-badge"><b>{new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',notation:'compact'}).format(revenue)}</b></span>}{properties.has('assignee')&&child.assignee&&<Avatar name={child.assignee.displayName}/>}</span></a>
}

function SubIssueDisplayMenu({value,onChange}:{value:SubIssueDisplay;onChange:(value:SubIssueDisplay)=>void}){const{t}=useI18n();const toggle=(property:SubIssueProperty)=>{const properties=new Set(value.properties);if(properties.has(property))properties.delete(property);else properties.add(property);onChange({...value,properties})};const names:Record<SubIssueProperty,string>={priority:'Priority',sla:'SLA',id:'ID',status:'Status',labels:'Labels',milestone:'Milestone',cycle:'Cycle',dueDate:'Due date',links:'Links',customers:'Customers',customerRevenue:'Customer revenue',assignee:'Assignee'};return <Popover.Root><Popover.Trigger asChild><button className="sub-issues-display" aria-label={t('Display options')}><DisplayIcon/></button></Popover.Trigger><Popover.Portal><Popover.Content className="sub-issues-display-menu" align="end" sideOffset={4}><label><span>{t('Ordering')}</span><span className="sub-issue-order"><SubIssueSelect ariaLabel={t('View ordering')} value={value.ordering} options={[{id:'priority',label:t('Priority')},{id:'created',label:t('Created')},{id:'updated',label:t('Updated')}]} onChange={ordering=>onChange({...value,ordering:ordering as SubIssueDisplay['ordering']})}/><button aria-label={t('Direction')} onClick={()=>onChange({...value,direction:value.direction==='asc'?'desc':'asc'})}>{value.direction==='asc'?'↑':'↓'}</button></span></label><label><span>{t('Completed issues')}</span><SubIssueSelect ariaLabel={t('Completed issues')} value={value.completed} options={[{id:'all',label:t('All')},{id:'none',label:t('None')}]} onChange={completed=>onChange({...value,completed:completed as SubIssueDisplay['completed']})}/></label><label><span>{t('Nested sub-issues')}</span><Toggle checked={value.nested} label={t('Nested sub-issues')} onChange={nested=>onChange({...value,nested})}/></label><h4>{t('Display properties')}</h4><div>{(Object.keys(names) as SubIssueProperty[]).map(property=><button aria-pressed={value.properties.has(property)} key={property} onClick={()=>toggle(property)}>{t(names[property])}</button>)}</div></Popover.Content></Popover.Portal></Popover.Root>}

function SubIssueSelect({ariaLabel,value,options,onChange}:{ariaLabel:string;value:string;options:{id:string;label:string}[];onChange:(value:string)=>void}){return <Select.Root value={value} onValueChange={onChange}><Select.Trigger className="sub-issue-select" aria-label={ariaLabel}><Select.Value/><Select.Icon><ChevronDown/></Select.Icon></Select.Trigger><Select.Portal><Select.Content className="sub-issue-select-menu" position="popper" sideOffset={4}><Select.Viewport>{options.map(option=><Select.Item className="sub-issue-select-item" value={option.id} key={option.id}><Select.ItemText>{option.label}</Select.ItemText><Select.ItemIndicator><Check/></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>}

function IssueProperties({issue,data,activities,releasesEnabled,onCreateMilestone,onCreateProject,onUpdate,onToggleLabel}:{issue:Issue;data:BootstrapData;activities:ActivityEvent[];releasesEnabled:boolean;onCreateMilestone?:(projectId:string,input:{name:string})=>Promise<ProjectMilestone>;onCreateProject?:(draft:NewProjectDraft)=>Promise<Project>;onUpdate:(i:IssueUpdateInput)=>Promise<void>;onToggleLabel:(id:string)=>Promise<void>}){const labels=labelsForResource(data.labels,'issue',data.labelGroups).filter(label=>!label.scope||label.scope==='Workspace'||label.scope===issue.team.id);const sla=data.issueSlas.find(item=>item.issueId===issue.id&&item.status!=='removed');const rule=sla?data.slaRules.find(item=>item.id===sla.ruleId):undefined;const member=issue.assignee?data.members.find(item=>item.user.id===issue.assignee?.id):undefined;const estimateType=data.teamSettings[issue.team.id]?.estimateType??'notUsed';return <aside className="issue-properties"><h3>Properties</h3><StatusPicker value={issue.state} states={statesForIssue(data,issue)} hoverHistory={{activities,issueCreatedAt:issue.createdAt}} onChange={stateId=>onUpdate({stateId})}/><PriorityPicker value={issue.priority} onChange={priority=>onUpdate({priority})}/>{estimateType!=='notUsed'&&<EstimatePicker value={issue.estimate} estimateType={estimateType} onChange={estimate=>onUpdate({estimate})}/>}<div className="issue-assignee-property"><AssigneePicker value={issue.assignee} users={data.users} hoverContext={{member,workspaceName:issue.team.name,project:issue.project}} onChange={assigneeId=>onUpdate({assigneeId})}/>{issue.assignee&&<a className="issue-assignee-profile" href={`/${data.workspace.urlKey}/members`} aria-label="Go to user"><ChevronRight size={15}/></a>}</div><CyclePicker valueId={issue.cycleId} cycles={data.cycles} issues={data.issues} teamId={issue.team.id} onChange={cycleId=>onUpdate({cycleId})}/>{sla&&<PropertyGroup title="SLA"><IssueSLAIndicator sla={sla} ruleName={rule?.name}/></PropertyGroup>}<PropertyGroup title="Labels"><LabelPicker inline value={issue.labels} labels={labels} labelGroups={data.labelGroups} onToggle={onToggleLabel}/></PropertyGroup><IssueProjectPicker grouped data={data} issue={issue} onCreateMilestone={onCreateMilestone} onCreateProject={onCreateProject} onUpdate={onUpdate}/>{issue.dueDate&&<PropertyGroup title="Due date"><DueDatePicker value={issue.dueDate} onChange={dueDate=>onUpdate({dueDate})}/></PropertyGroup>}{releasesEnabled&&<IssueReleasePicker grouped data={data} issue={issue}/>}</aside>}
function PropertyGroup({title,children}:{title:string;children:React.ReactNode}){return <section className="property-group"><h4>{title}</h4>{children}</section>}
function IssueSection({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="issue-detail-section"><header><strong>{title}</strong><span>{count}</span></header>{children}</section>}
function IssueParentContext({parent,issues,workspaceKey,onOpen}:{parent:Issue;issues:Issue[];workspaceKey:string;onOpen:()=>void}){const children=parent.subIssueIds.map(id=>issues.find(issue=>issue.id===id)).filter((issue):issue is Issue=>Boolean(issue)&&!issue!.archivedAt),completed=children.filter(issue=>issue.state.type==='completed'||issue.state.type==='canceled').length;return <div className="issue-parent-context"><span>Sub-issue of</span><a href={`/${workspaceKey}/issue/${parent.identifier}`} onClick={event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();onOpen()}}><StatusIcon state={parent.state} size={14}/><strong data-i18n-ignore>{parent.identifier}</strong><span data-i18n-ignore>{parent.title}</span></a>{children.length>0&&<button aria-label={`Open sub-issues of ${parent.identifier}`} onClick={onOpen}><SubIssueProgressRing completed={completed} total={children.length}/><span>{completed}/{children.length}</span></button>}</div>}
function IssueResources({documents,links,workspaceKey,actions,onDeleteLink}:{documents:FlowDocument[];links:Attachment[];workspaceKey:string;actions?:IssueOptionsActions;onDeleteLink:(id:string)=>Promise<void>}){
  const[collapsed,setCollapsed]=useState(false),[menuOpen,setMenuOpen]=useState(false),[linkOpen,setLinkOpen]=useState(false),[url,setUrl]=useState(''),[title,setTitle]=useState(''),[saving,setSaving]=useState(false)
  const addLink=async()=>{if(!actions||!url.trim())return;setSaving(true);try{await actions.addLink({url:url.trim(),title:title.trim()||undefined});setUrl('');setTitle('');setLinkOpen(false)}finally{setSaving(false)}}
  return <section className="issue-detail-section issue-resources"><header><button className="issue-section-collapse" aria-label={collapsed?'Expand resources section':'Collapse resources section'} aria-expanded={!collapsed} onClick={()=>setCollapsed(value=>!value)}><ChevronDown/><span>Resources</span></button><span>{documents.length+links.length}</span><span/><Popover.Root open={menuOpen} onOpenChange={setMenuOpen}><Popover.Trigger asChild><button className="issue-section-add" aria-label="Add resource to issue"><Plus/></button></Popover.Trigger><Popover.Portal><Popover.Content className="issue-resource-menu" align="end" sideOffset={4}><button onClick={()=>{setMenuOpen(false);void actions?.addDocument()}} disabled={!actions}><FileText/>Create document</button><button onClick={()=>{setMenuOpen(false);setLinkOpen(true)}} disabled={!actions}><Link2/>Add link</button></Popover.Content></Popover.Portal></Popover.Root></header>{!collapsed&&<>{documents.map(document=><a className="linked-issue issue-resource-row" href={documentPath(workspaceKey,document)} key={document.id}><FileText size={14}/><span>Document</span><strong data-i18n-ignore>{document.title}</strong></a>)}{links.map(link=><a className="linked-issue issue-resource-row" href={link.url} target="_blank" rel="noreferrer" key={link.id}><Link2 size={14}/><span>{safeHost(link.url)}</span><strong data-i18n-ignore>{link.title}</strong><button aria-label={`Delete resource ${link.title}`} onClick={event=>{event.preventDefault();event.stopPropagation();void onDeleteLink(link.id)}}><X/></button></a>)}</>}
    <Dialog.Root open={linkOpen} onOpenChange={setLinkOpen}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="issue-link-dialog"><Dialog.Title>Add link</Dialog.Title><label>URL<input autoFocus type="url" value={url} placeholder="https://" onChange={event=>setUrl(event.target.value)}/></label><label>Title<input value={title} placeholder="Optional" onChange={event=>setTitle(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&url.trim())void addLink()}}/></label><footer><Dialog.Close asChild><button>Cancel</button></Dialog.Close><button className="primary" disabled={!url.trim()||saving} onClick={()=>void addLink()}>{saving?'Adding…':'Add link'}</button></footer></Dialog.Content></Dialog.Portal></Dialog.Root>
  </section>
}
function safeHost(value:string){try{return new URL(value).hostname}catch{return 'Link'}}
function relationLabel(type:IssueRelationType){return type==='blocked_by'?'Blocked by':type==='blocks'?'Blocking':type==='duplicate'?'Duplicate of':type==='parent_of'?'Parent of':type==='sub_issue_of'?'Sub-issue of':'Related'}
function statesForIssue(data:BootstrapData,issue:Issue){const specific=data.states.some(state=>state.teamId===issue.team.id);return data.states.filter(state=>specific?state.teamId===issue.team.id:!state.teamId).sort((left,right)=>(left.position??0)-(right.position??0))}
