import { ChevronRight, Menu, Star } from 'lucide-react'
import { useMemo } from 'react'

import type { Cycle, CycleMutationInput, CycleSettingsMutationInput, Issue, Team } from '@/types/flow'
import { useI18n } from '@/i18n/i18n'
import { CycleActions } from './cycle-menus'
import { cycleStats, formatCycleDay } from './cycle-model'

import './cycles.css'

export function CyclesPage({cycles,issues,settings,onOpen,onUpdateCycle,onStartCycle,onCompleteCycle,onUpdateSettings,onReload,onOpenSidebar}:{cycles:Cycle[];issues:Issue[];settings:{enabled:boolean;durationWeeks:number;cooldownWeeks:number;upcomingCount:number;favoriteView?:boolean};team:Team;onOpen:(cycle:Cycle)=>void;onUpdateCycle:(cycle:Cycle,input:CycleMutationInput)=>Promise<unknown>;onStartCycle:(cycle:Cycle)=>Promise<unknown>;onCompleteCycle:(cycle:Cycle)=>Promise<unknown>;onUpdateSettings:(input:CycleSettingsMutationInput)=>Promise<unknown>;onReload:()=>Promise<void>;onOpenSidebar:()=>void}){
  const {t}=useI18n()
  const visible=useMemo(()=>[...cycles].sort((a,b)=>b.startsAt.localeCompare(a.startsAt)),[cycles])
  const earliestUpcoming=[...visible].filter(item=>item.status==='upcoming').sort((a,b)=>a.startsAt.localeCompare(b.startsAt))[0]?.id
  return <main className="main-panel flow-cycles-page"><header className="flow-cycles-header"><button className="cycles-mobile-menu" aria-label={t('Open sidebar')} onClick={onOpenSidebar}><Menu/></button><h1>{t('Cycles')}</h1><button className="cycle-top-icon" role="switch" aria-label={t(settings.favoriteView?'Remove from favorites':'Add to favorites')} aria-checked={Boolean(settings.favoriteView)} onClick={()=>void onUpdateSettings({favoriteView:!settings.favoriteView})}><Star fill={settings.favoriteView?'currentColor':'none'}/></button></header>{!settings.enabled||!visible.length?<div className="flow-cycles-empty"><strong>{t('This team has no cycles.')}</strong></div>:<div className="flow-cycle-list">{visible.map(cycle=><CycleDirectoryRow key={cycle.id} cycle={cycle} issues={issues} derivedStatus={cycle.status==='upcoming'&&cycle.id!==earliestUpcoming?'planned':cycle.status} onOpen={()=>onOpen(cycle)} onUpdate={input=>onUpdateCycle(cycle,input)} onStart={()=>onStartCycle(cycle)} onComplete={()=>onCompleteCycle(cycle)} onReload={onReload}/>)}</div>}</main>
}

function CycleDirectoryRow({cycle,issues,derivedStatus,onOpen,onUpdate,onStart,onComplete,onReload}:{cycle:Cycle;issues:Issue[];derivedStatus:string;onOpen:()=>void;onUpdate:(input:CycleMutationInput)=>Promise<unknown>;onStart:()=>Promise<unknown>;onComplete:()=>Promise<unknown>;onReload:()=>Promise<void>}){
  const {t}=useI18n(),start=formatCycleDay(cycle.startsAt),stats=cycleStats(cycle,issues)
  const metric=cycle.status==='current'?`${weekdays(cycle.endsAt)} ${t('weekdays left')}`:cycle.status==='completed'?`${stats.successPercent}% ${t('success')}`:`${stats.scope} ${t('scope')}`
  return <div className="flow-cycle-row" data-current={cycle.status==='current'}><button className="flow-cycle-row-link" onClick={onOpen}><span className="flow-cycle-date"><b>{start.month}</b><strong>{start.day}</strong></span><span className="flow-cycle-arrow"><ChevronRight/></span><strong className="flow-cycle-name" data-i18n-ignore>{cycle.name}</strong><span className={`flow-cycle-status is-${derivedStatus}`}>{t(statusText(derivedStatus))}</span><span className="flow-cycle-capacity"><i style={{'--capacity':`${Math.min(100,stats.capacityPercent)*3.6}deg`} as React.CSSProperties}/><b>{stats.capacityPercent}%</b><em>{t('of capacity')}</em></span><span className="flow-cycle-scope">{metric}</span></button><CycleActions cycle={cycle} onUpdate={onUpdate} onStart={onStart} onComplete={onComplete} onReload={onReload} canonicalPath={location.pathname.replace(/\/cycles$/,`/cycle/${cycle.number}`)}/>{cycle.status==='current'&&<CycleDirectorySummary cycle={cycle} stats={stats}/>}</div>
}

function CycleDirectorySummary({cycle,stats}:{cycle:Cycle;stats:ReturnType<typeof cycleStats>}){const{t,formatDate}=useI18n(),start=new Date(cycle.startsAt),end=new Date(cycle.endsAt),middle=new Date((start.getTime()+end.getTime())/2);return <div className="flow-cycle-current-summary"><div className="flow-cycle-current-metrics"><span><small>{t('Scope')}</small><strong>{stats.scope}</strong></span><span><small>{t('Started')}</small><strong>{stats.started}</strong><em>• {stats.startedPercent}%</em></span><span><small>{t('Completed')}</small><strong>{stats.completed}</strong><em>• {stats.completedPercent}%</em></span></div><div className="flow-cycle-current-chart" aria-label={t('Cycle progress')}><svg viewBox="0 0 600 92" preserveAspectRatio="none"><path className="baseline" d="M0 70H600"/><path className="scope" d={`M0 70 C150 ${70-Math.min(48,stats.scope*2)}, 420 ${70-Math.min(48,stats.scope*2)}, 600 ${70-Math.min(48,stats.scope*2)}`}/><path className="completed" d={`M0 70 C180 ${70-Math.min(48,stats.completed*3)}, 430 ${70-Math.min(48,stats.completed*3)}, 600 ${70-Math.min(48,stats.completed*3)}`}/></svg><div><time>{formatDate(start,{month:'short',day:'numeric'})}</time><time>{formatDate(middle,{month:'short',day:'numeric'})}</time><time>{formatDate(end,{month:'short',day:'numeric'})}</time></div></div></div>}

function statusText(status:string){return status==='current'?'Active':status==='completed'?'Completed':status==='planned'?'Planned':'Upcoming'}
function weekdays(end:string){const cursor=new Date(),last=new Date(end);let count=0;cursor.setHours(0,0,0,0);while(cursor<=last){if(cursor.getDay()!==0&&cursor.getDay()!==6)count++;cursor.setDate(cursor.getDate()+1)}return Math.max(0,count)}
