import { describe, expect, it } from 'vitest'
import { render, screen } from '@testing-library/react'
import { FeedItemByline, FeedItemContent, FeedItemHeader, FeedItemTitle, feedItemSharedLabel } from './feed-item-common'

describe('FeedItemCommon (LS-0265)', () => {
  it('labels shared update types', () => {
    expect(feedItemSharedLabel('summary')).toBe('generated')
    expect(feedItemSharedLabel('projectUpdate')).toBe('a project update')
    expect(feedItemSharedLabel('initiativeUpdate')).toBe('an initiative update')
    expect(feedItemSharedLabel('update', 'Platform')).toBe('an update in Platform')
  })

  it('renders Generated byline for summary type', () => {
    render(<FeedItemByline date="2026-09-20T12:00:00.000Z" type="summary" />)
    expect(screen.getByText('Generated')).toBeTruthy()
  })

  it('renders author shared byline for project updates', () => {
    render(
      <FeedItemByline
        author={{ id: 'u1', name: 'Ada', displayName: 'Ada', email: 'a@x', avatarUrl: '', active: true, emailVerified: true }}
        date="2026-09-20T12:00:00.000Z"
        type="projectUpdate"
      />,
    )
    expect(screen.getByText('Ada')).toBeTruthy()
    expect(screen.getByText(/shared a project update/)).toBeTruthy()
  })

  it('composes header title + byline + content', () => {
    render(
      <FeedItemHeader
        byline={<FeedItemByline date="2026-09-20T12:00:00.000Z" type="summary" />}
        title={<FeedItemTitle>Weekly summary</FeedItemTitle>}
      />,
    )
    expect(screen.getByText('Weekly summary')).toBeTruthy()
    render(<FeedItemContent>Body</FeedItemContent>)
    expect(screen.getByText('Body')).toBeTruthy()
  })
})
