import { Archive, Bot, Check, Trash2, X } from 'lucide-react'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Button } from '@/components/ui/button'
import type { BootstrapData, IssueUpdateInput } from '@/types/flow'
import { CalendarIcon, LabelIcon, NoAssigneeIcon, NoProjectIcon, PriorityIcon, ProjectIcon } from '@/components/issue/issue-icons'
import { labelsForResource } from '@/lib/labels'

export function BulkActionBar({count,data,onUpdate,onToggleLabel,onDelete,onClear}:{count:number;data:BootstrapData;onUpdate:(input:IssueUpdateInput)=>void;onToggleLabel:(labelId:string)=>void;onDelete:()=>void;onClear:()=>void}){
  if(!count)return null
  const issueLabels=labelsForResource(data.labels,'issue',data.labelGroups)
  return <div className="bulk-bar"><strong>{count}</strong><span>selected</span><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline">Actions</Button></DropdownMenuTrigger><DropdownMenuContent align="center" className="bulk-menu"><DropdownMenuLabel>Update issues</DropdownMenuLabel><ChoiceSub icon={<Check size={14}/>} label="Status" items={data.states.map(s=>({id:s.id,label:s.name,color:s.color}))} onSelect={stateId=>onUpdate({stateId})}/><ChoiceSub icon={<PriorityIcon priority={0} size={14}/>} label="Priority" items={['No priority','Urgent','High','Medium','Low'].map((label,id)=>({id:String(id),label,icon:<PriorityIcon priority={id} size={14}/>}))} onSelect={priority=>onUpdate({priority:+priority})}/><ChoiceSub icon={<NoAssigneeIcon size={14}/>} label="Assignee" items={[{id:'',label:'No assignee',icon:<NoAssigneeIcon size={14}/>},...data.users.map(u=>({id:u.id,label:u.displayName}))]} onSelect={assigneeId=>onUpdate({assigneeId})}/><ChoiceSub icon={<LabelIcon size={14}/>} label="Labels" items={issueLabels.map(l=>({id:l.id,label:l.name,color:l.color}))} onSelect={onToggleLabel}/><ChoiceSub icon={<ProjectIcon size={14}/>} label="Project" items={[{id:'',label:'No project',icon:<NoProjectIcon size={14}/>},...data.projects.map(p=>({id:p.id,label:p.name,color:p.color,icon:<ProjectIcon size={14} style={{color:p.color}}/>}))]} onSelect={projectId=>onUpdate({projectId})}/><DropdownMenuItem onSelect={()=>onUpdate({dueDate:new Date().toISOString().slice(0,10)})}><CalendarIcon size={14}/>Due today</DropdownMenuItem><DropdownMenuItem onSelect={()=>onUpdate({archived:true})}><Archive size={14}/>Archive</DropdownMenuItem><DropdownMenuItem className="danger" onSelect={onDelete}><Trash2 size={14}/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button variant="ghost"><Bot size={14}/>Ask Flow</Button><Button variant="ghost" size="icon" aria-label="Clear selected" onClick={onClear}><X size={14}/></Button></div>
}

function ChoiceSub({icon,label,items,onSelect}:{icon:React.ReactNode;label:string;items:{id:string;label:string;color?:string;icon?:React.ReactNode}[];onSelect:(id:string)=>void}){return <DropdownMenuSub><DropdownMenuSubTrigger>{icon}{label}</DropdownMenuSubTrigger><DropdownMenuSubContent>{items.map(item=><DropdownMenuItem key={item.id} onSelect={()=>onSelect(item.id)}>{item.icon ?? (item.color&&<i className="option-dot" style={{background:item.color}}/>)}{item.label}</DropdownMenuItem>)}</DropdownMenuSubContent></DropdownMenuSub>}
