import { ArrowDown, ArrowUp, Check, MoreHorizontal, Plus, Search, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { toast } from 'sonner'

import { createLabelGroup, createProjectStatus, createWorkspaceLabel, deleteLabelGroup, deleteProjectStatus, deleteWorkspaceLabel, reorderProjectStatuses, updateLabelGroup, updateProjectStatus, updateWorkspaceLabel } from '@/lib/api'
import type { BootstrapData, IssueLabel, LabelGroup, ProjectStatus } from '@/types/flow'

export function DomainLabelsSettings({ data, resourceType, onReload }: { data: BootstrapData; resourceType: 'issue'|'project'; onReload: () => Promise<void> }) {
  const [query,setQuery]=useState(''); const [creating,setCreating]=useState(false); const [creatingGroup,setCreatingGroup]=useState(false)
  const labels=useMemo(()=>data.labels.filter(item=>(item.resourceType??'issue')===resourceType&&!item.scope&&item.name.toLowerCase().includes(query.toLowerCase())),[data.labels,query,resourceType])
  const groups=data.labelGroups.filter(item=>item.resourceType===resourceType&&!item.scope)
  const run=async(action:()=>Promise<unknown>)=>{try{await action();await onReload()}catch(error){toast.error(message(error))}}
  return <><header className="settings-page-header"><div><h1>{resourceType==='issue'?'Issue':'Project'} labels</h1><p>Organize {resourceType}s with workspace labels and label groups.</p></div><div className="settings-header-actions"><button className="settings-action" onClick={()=>setCreatingGroup(true)}><Plus size={14}/>New group</button><button className="settings-action primary" onClick={()=>setCreating(true)}><Plus size={14}/>New label</button></div></header>
    <div className="settings-list-toolbar"><Search size={14}/><input aria-label="Filter by name" placeholder="Filter by name…" value={query} onChange={event=>setQuery(event.target.value)}/></div>
    {creatingGroup&&<GroupEditor resourceType={resourceType} onCancel={()=>setCreatingGroup(false)} onSave={async input=>{await run(()=>createLabelGroup(input));setCreatingGroup(false)}}/>}
    {groups.map(group=><GroupRow key={group.id} group={group} onSave={input=>run(()=>updateLabelGroup(group.id,input))} onDelete={()=>run(()=>deleteLabelGroup(group.id))}/>) }
    <section className="settings-section"><div className="settings-card advanced-settings-list">
      {creating&&<LabelEditor groups={groups} onCancel={()=>setCreating(false)} onSave={async input=>{await run(()=>createWorkspaceLabel({...input,resourceType}));setCreating(false)}}/>}
      {labels.map(label=><LabelRow key={label.id} data={data} label={label} groups={groups} resourceType={resourceType} onSave={input=>run(()=>updateWorkspaceLabel(label.id,input))} onDelete={()=>run(()=>deleteWorkspaceLabel(label.id))}/>) }
      {!labels.length&&!creating&&<div className="advanced-settings-empty"><span>No {resourceType} labels</span></div>}
    </div></section></>
}

function LabelEditor({groups,onCancel,onSave}:{groups:LabelGroup[];onCancel:()=>void;onSave:(input:{name:string;description:string;color:string;groupId?:string})=>Promise<void>}){const[name,setName]=useState('');const[description,setDescription]=useState('');const[color,setColor]=useState('#5E6AD2');const[groupId,setGroupId]=useState('');return <div className="advanced-settings-editor label-editor"><div className="advanced-settings-fields"><input type="color" value={color} onChange={event=>setColor(event.target.value)}/><input autoFocus placeholder="Label name" value={name} onChange={event=>setName(event.target.value)}/><select value={groupId} onChange={event=>setGroupId(event.target.value)}><option value="">No group</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select></div><textarea placeholder="Label description…" value={description} onChange={event=>setDescription(event.target.value)}/><footer><button onClick={onCancel}><X size={14}/>Cancel</button><button className="primary" disabled={!name.trim()} onClick={()=>void onSave({name:name.trim(),description,color,groupId:groupId||undefined})}><Check size={14}/>Create</button></footer></div>}

function LabelRow({data,label,groups,resourceType,onSave,onDelete}:{data:BootstrapData;label:IssueLabel;groups:LabelGroup[];resourceType:'issue'|'project';onSave:(input:Partial<IssueLabel>)=>Promise<void>;onDelete:()=>Promise<void>}){const[name,setName]=useState(label.name);const[description,setDescription]=useState(label.description??'');const count=resourceType==='issue'?data.issues.filter(issue=>issue.labels.some(item=>item.id===label.id)).length:data.projects.filter(project=>project.labelIds.includes(label.id)).length;return <div className="settings-list-row domain-label-row"><input aria-label={`${label.name} color`} type="color" value={label.color} onChange={event=>void onSave({color:event.target.value})}/><input aria-label={`${label.name} name`} value={name} onChange={event=>setName(event.target.value)} onBlur={()=>name.trim()!==label.name&&void onSave({name:name.trim()})}/><input aria-label={`${label.name} description`} placeholder="Add label description…" value={description} onChange={event=>setDescription(event.target.value)} onBlur={()=>description!==label.description&&void onSave({description})}/><select aria-label={`${label.name} group`} value={label.groupId??''} onChange={event=>void onSave({groupId:event.target.value})}><option value="">No group</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><span>{count} {resourceType}{count===1?'':'s'}</span><button aria-label={`Delete ${label.name}`} onClick={()=>void onDelete()}><Trash2 size={14}/></button></div>}

function GroupEditor({resourceType,onCancel,onSave}:{resourceType:'issue'|'project';onCancel:()=>void;onSave:(input:{name:string;color:string;resourceType:'issue'|'project'})=>Promise<void>}){const[name,setName]=useState('');const[color,setColor]=useState('#8b8d98');return <section className="settings-section"><div className="settings-card advanced-settings-editor"><div className="advanced-settings-fields"><input type="color" value={color} onChange={event=>setColor(event.target.value)}/><input autoFocus placeholder="Group name" value={name} onChange={event=>setName(event.target.value)}/></div><footer><button onClick={onCancel}>Cancel</button><button className="primary" disabled={!name.trim()} onClick={()=>void onSave({name:name.trim(),color,resourceType})}>Create group</button></footer></div></section>}
function GroupRow({group,onSave,onDelete}:{group:LabelGroup;onSave:(input:Partial<LabelGroup>)=>Promise<void>;onDelete:()=>Promise<void>}){const[name,setName]=useState(group.name);return <section className="settings-section"><div className="settings-card"><div className="settings-row"><input type="color" aria-label={`${group.name} color`} value={group.color} onChange={event=>void onSave({color:event.target.value})}/><input className="settings-input" value={name} onChange={event=>setName(event.target.value)} onBlur={()=>name.trim()!==group.name&&void onSave({name:name.trim()})}/><button className="settings-icon-action" aria-label={`Delete ${group.name}`} onClick={()=>void onDelete()}><Trash2 size={14}/></button></div></div></section>}

export function ProjectStatusesSettings({data,onReload}:{data:BootstrapData;onReload:()=>Promise<void>}){const[creating,setCreating]=useState(false);const statuses=[...data.projectStatuses].sort((a,b)=>(a.position??0)-(b.position??0));const run=async(action:()=>Promise<unknown>)=>{try{await action();await onReload()}catch(error){toast.error(message(error))}};const move=(index:number,delta:number)=>{const next=[...statuses];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];void run(()=>reorderProjectStatuses(next.map(item=>item.id)))};return <><header className="settings-page-header"><div><h1>Project statuses</h1><p>Project statuses define the workflow projects move through.</p></div><button className="settings-action primary" onClick={()=>setCreating(true)}><Plus size={14}/>New status</button></header><section className="settings-section"><div className="settings-card advanced-settings-list">{creating&&<StatusEditor onCancel={()=>setCreating(false)} onSave={async input=>{await run(()=>createProjectStatus(input));setCreating(false)}}/>}{statuses.map((status,index)=><StatusRow key={status.id} status={status} first={index===0} last={index===statuses.length-1} onMove={delta=>move(index,delta)} onSave={input=>run(()=>updateProjectStatus(status.id,input))} onDelete={()=>run(()=>deleteProjectStatus(status.id))}/> )}</div></section></>}
function StatusEditor({onCancel,onSave}:{onCancel:()=>void;onSave:(input:{name:string;color:string;type:string})=>Promise<void>}){const[name,setName]=useState('');const[color,setColor]=useState('#8b8d98');const[type,setType]=useState('planned');return <div className="advanced-settings-editor"><div className="advanced-settings-fields"><input type="color" value={color} onChange={event=>setColor(event.target.value)}/><input autoFocus placeholder="Status name" value={name} onChange={event=>setName(event.target.value)}/><select value={type} onChange={event=>setType(event.target.value)}>{['backlog','planned','started','completed','canceled'].map(value=><option key={value}>{value}</option>)}</select></div><footer><button onClick={onCancel}>Cancel</button><button className="primary" disabled={!name.trim()} onClick={()=>void onSave({name:name.trim(),color,type})}>Create</button></footer></div>}
function StatusRow({status,first,last,onMove,onSave,onDelete}:{status:ProjectStatus;first:boolean;last:boolean;onMove:(delta:number)=>void;onSave:(input:Partial<ProjectStatus>)=>Promise<void>;onDelete:()=>Promise<void>}){const[name,setName]=useState(status.name);return <div className="settings-list-row project-status-setting"><input type="color" value={status.color} onChange={event=>void onSave({color:event.target.value})}/><input value={name} onChange={event=>setName(event.target.value)} onBlur={()=>name.trim()!==status.name&&void onSave({name:name.trim()})}/><select value={status.type} onChange={event=>void onSave({type:event.target.value})}>{['backlog','planned','started','completed','canceled'].map(value=><option key={value}>{value}</option>)}</select><button disabled={first} aria-label="Move status up" onClick={()=>onMove(-1)}><ArrowUp size={14}/></button><button disabled={last} aria-label="Move status down" onClick={()=>onMove(1)}><ArrowDown size={14}/></button><button aria-label={`Delete ${status.name}`} onClick={()=>void onDelete()}><Trash2 size={14}/></button></div>}
function message(error:unknown){return error instanceof Error?error.message:'Could not save setting'}
