import { useEffect, useState, type ComponentType } from 'react'
import { ArrowLeft, Bot, Check, ChevronRight, Circle, GitBranch, GripVertical, MoreHorizontal, Plus, Sparkles, Trash2, WandSparkles, X } from 'lucide-react'
import { toast } from 'sonner'

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import {
  createDocumentTemplate, createIssue, createTeamLabel, createTriageResponsibility, createTriageRule, createWorkflowState, deleteDocumentTemplate, deleteTeamLabel, deleteTriageResponsibility, deleteTriageRule, deleteWorkflowState,
  fetchWorkflowStates, reorderWorkflowStates, setTeamMembership, updateCycleSettings,
  updateDocumentTemplate, updateIssue, updateStructuredTeamSettings, updateTeam, updateTeamLabel, updateWorkflowState,
} from '@/lib/api'
import type { BootstrapData, CycleSettings, DocumentTemplate, IssueLabel, IssueTemplate, ProjectTemplate, Team, TeamSettings, WorkflowState, WorkflowStateType } from '@/types/flow'
import type { TeamSettingsSection } from '@/lib/app-routes'
import { TemplateEditor } from './advanced-settings'
import { SettingsRow, SettingsSection, SettingsToggle } from './settings-primitives'
import { CheckboxMark } from '@/components/ui/checkbox-mark'

const SECTIONS: { id: TeamSettingsSection; label: string; description: string }[] = [
  { id: 'general', label: 'General', description: 'Name, identifier, timezone, and issue defaults' },
  { id: 'security', label: 'Access and permissions', description: 'Team access and management permissions' },
  { id: 'members', label: 'Members', description: 'Manage who belongs to this team' },
  { id: 'notifications', label: 'Slack notifications', description: 'Send team activity to Slack' },
  { id: 'issue-labels', label: 'Issue labels', description: 'Team-scoped labels' },
  { id: 'templates', label: 'Templates', description: 'Issue, project, and document templates' },
  { id: 'recurring-issues', label: 'Recurring issues', description: 'Issues recreated on a schedule' },
  { id: 'statuses', label: 'Issue statuses', description: 'Workflow states and ordering' },
  { id: 'workflow', label: 'Workflows and automations', description: 'PR, closing, and archive automations' },
  { id: 'triage', label: 'Triage', description: 'Route and prioritize incoming issues' },
  { id: 'cycles', label: 'Cycles', description: 'Cycle schedule and automations' },
  { id: 'agents', label: 'Team agents', description: 'Connected agents available to the team' },
  { id: 'agent-skills', label: 'Agent skills', description: 'Reusable team instructions for agents' },
  { id: 'ai-updates', label: 'Project updates prompt', description: 'Guidance used for generated project updates' },
  { id: 'ai-summaries', label: 'Resolved thread summaries', description: 'Summarize resolved comment threads' },
]
const STATUS_GROUPS: { type: WorkflowStateType; label: string; reserved?: boolean }[] = [
  { type: 'backlog', label: 'Backlog' }, { type: 'unstarted', label: 'Unstarted' }, { type: 'started', label: 'Started' }, { type: 'completed', label: 'Completed' }, { type: 'canceled', label: 'Canceled' }, { type: 'canceled', label: 'Duplicate', reserved: true },
]

export function TeamWorkflowSettings({ data, team, section, onNavigate, onReload }: { data: BootstrapData; team: Team; section: TeamSettingsSection; onNavigate: (section: TeamSettingsSection) => void; onReload: () => Promise<void> }) {
  const Content = TEAM_SECTION_COMPONENTS[section]
  return <>
    <header className="settings-page-header team-settings-header"><div>{section !== 'overview' && <button className="settings-icon-action team-settings-back" aria-label="Back to team settings" onClick={() => onNavigate('overview')}><ArrowLeft size={15}/></button>}<span className="settings-team-icon large" style={{ color: team.color }}>{team.icon || team.key[0]}</span><h1>{section === 'overview' ? team.name : SECTIONS.find(item => item.id === section)?.label}</h1></div></header>
    {section === 'overview' && <TeamOverview data={data} team={team} onNavigate={onNavigate} onReload={onReload}/>}
    {section === 'agents' && <TeamAgentsSettings data={data}/>}
    {Content && <Content data={data} team={team} onReload={onReload}/>}
  </>
}

type TeamSectionComponent = ComponentType<{data:BootstrapData;team:Team;onReload:()=>Promise<void>}>
const TEAM_SECTION_COMPONENTS: Partial<Record<TeamSettingsSection,TeamSectionComponent>> = {
  general:GeneralSettings,security:AccessSettings,members:MembersSettings,notifications:SlackSettings,'issue-labels':LabelsSettings,templates:TemplatesSettings,'recurring-issues':RecurringIssuesSettings,statuses:StatusesSettings,workflow:WorkflowSettings,triage:TriageSettings,cycles:CyclesSettings,'agent-skills':AgentSkillsSettings,'ai-updates':ProjectUpdatePromptSettings,'ai-summaries':ResolvedSummariesSettings,
}

function useTeamSettings(data: BootstrapData, team: Team, onReload: () => Promise<void>) {
  const [settings, setSettings] = useState(data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states))
  useEffect(() => setSettings(data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states)), [data.states, data.teamSettings, team.id])
  const save = async (patch: Partial<TeamSettings>) => {
    const previous = settings; setSettings({ ...settings, ...patch })
    try { const next = await updateStructuredTeamSettings(team.id, patch); setSettings(next); await onReload() }
    catch (error) { setSettings(previous); toast.error(message(error)) }
  }
  return { settings, setSettings, save }
}

function TeamOverview({ data, team, onNavigate, onReload }: { data: BootstrapData; team: Team; onNavigate: (section: TeamSettingsSection) => void; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  return <><TeamSection><div className="team-overview-list">{SECTIONS.map(item => <button key={item.id} onClick={() => onNavigate(item.id)}><span><strong>{item.label}</strong><small>{item.description}</small></span><ChevronRight size={15}/></button>)}</div></TeamSection><TeamSection title="Team hierarchy"><SelectRow title="Parent team" value={settings.parentTeamId ?? ''} options={['', ...data.teams.filter(item => item.id !== team.id).map(item => item.id)]} labels={{ '': 'No parent team', ...Object.fromEntries(data.teams.map(item => [item.id, item.name])) }} onChange={value => save({ parentTeamId: value })}/><ToggleRow title="Show initiatives in sidebar" checked={settings.showInitiatives} onChange={value => save({ showInitiatives: value })}/></TeamSection></>
}

function GeneralSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const initial = data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states)
  const [settings, setSettings] = useState(initial)
  const [name, setName] = useState(team.name); const [identifier, setIdentifier] = useState(team.key)
  useEffect(() => { setSettings(data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states)); setName(team.name); setIdentifier(team.key) }, [data.states, data.teamSettings, team.id, team.key, team.name])
  const save = async (patch: Partial<TeamSettings> & { identifier?: string }) => { try { setSettings(await updateStructuredTeamSettings(team.id, patch)); await onReload(); toast.success('Team settings saved') } catch (error) { toast.error(message(error)) } }
  return <>
    <TeamSection title="Icon & Name"><TeamRow title="Team icon"><span className="settings-team-icon large" style={{ color: team.color }}>{team.icon || team.key[0]}</span></TeamRow><InputRow title="Name" value={name} onChange={setName} onCommit={async value => { await updateTeam(data.workspace.urlKey, team.id, { name: value }); await onReload() }}/></TeamSection>
    <TeamSection title="General"><InputRow title="Identifier" description="Used as the prefix for new issue identifiers. Existing issue identifiers won't change." value={identifier} onChange={value => setIdentifier(value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5))} onCommit={value => save({ identifier: value })}/><InputRow title="Description" value={settings.description ?? ''} onChange={value => setSettings(current => ({ ...current, description: value }))} onCommit={value => save({ description: value })}/><SelectRow title="Timezone" description="Used when scheduling cycles and team automations." value={settings.timezone} options={['Etc/UTC','Asia/Shanghai','America/Los_Angeles','Europe/London']} onChange={value => save({ timezone: value })}/></TeamSection>
    <TeamSection title="Issues"><SelectRow title="Issue estimation" value={settings.estimateType} options={['notUsed','exponential','fibonacci','flow']} labels={{ notUsed: 'Not used', exponential: 'Exponential', fibonacci: 'Fibonacci', flow: 'Flow' }} onChange={value => save({ estimateType: value as TeamSettings['estimateType'] })}/><SelectRow title="Default status" value={settings.defaultStateId} options={statesForTeam(data, team.id).map(state => state.id)} labels={Object.fromEntries(statesForTeam(data, team.id).map(state => [state.id, state.name]))} onChange={value => save({ defaultStateId: value })}/><SelectRow title="Default priority" value={String(settings.defaultPriority)} options={['0','4','3','2','1']} labels={{ '0': 'No priority', '4': 'Low', '3': 'Medium', '2': 'High', '1': 'Urgent' }} onChange={value => save({ defaultPriority: Number(value) })}/><ToggleRow title="Create issues by email" description="Accept new team issues at a generated email address." checked={settings.issueEmailEnabled} onChange={value => save({ issueEmailEnabled: value })}/><ToggleRow title="Detailed issue history" description="Keep a full record of issue property changes." checked={settings.detailedHistory} onChange={value => save({ detailedHistory: value })}/></TeamSection>
  </>
}

function AccessSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  const permissionLabels = { allMembers: 'All workspace members', teamMembers: 'Team members', owners: 'Team owners' }
  const permissionOptions = Object.keys(permissionLabels)
  return <><TeamSection title="Team access"><SelectRow title="Team visibility" description="Private teams are visible only to members." value={settings.access} options={['public','private']} labels={{ public: 'Public', private: 'Private' }} onChange={value => save({ access: value as TeamSettings['access'] })}/><SelectRow title="Who can join" value={settings.membershipRestriction} options={['open','members','owners']} labels={{ open: 'Anyone in the workspace', members: 'By invitation', owners: 'Team owners only' }} onChange={value => save({ membershipRestriction: value as TeamSettings['membershipRestriction'] })}/></TeamSection><TeamSection title="Management permissions">{([
    ['settingsPermission','Change team settings'], ['labelPermission','Manage labels'], ['templatePermission','Manage templates'], ['agentSkillPermission','Manage agent skills'], ['loopPermission','Create Loops'], ['memberPermission','Manage members'],
  ] as const).map(([key, label]) => <SelectRow key={key} title={label} value={settings[key]} options={permissionOptions} labels={permissionLabels} onChange={value => save({ [key]: value } as Partial<TeamSettings>)}/>)}</TeamSection></>
}

function SlackSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  const slack = data.integrationConnections.find(item => item.provider.toLowerCase() === 'slack' && item.status === 'connected')
  const choices = [['issueCreated','Issue created'],['issueCompleted','Issue completed'],['issueCanceled','Issue canceled'],['commentCreated','New comments'],['projectUpdates','Project updates'],['cycleUpdates','Cycle updates']] as const
  return <><TeamSection title="Slack connection"><TeamRow title="Workspace connection" description={slack ? `Connected as ${slack.name}` : 'Connect Slack from workspace Integrations before choosing a channel.'}><span className="settings-static">{slack ? 'Connected' : 'Not connected'}</span></TeamRow><InputRow title="Channel" description="Slack channel name, for example #engineering" value={settings.slackChannelName ?? ''} onChange={value => void save({ slackChannelName: value })} onCommit={() => undefined}/></TeamSection><div className={!slack || !settings.slackChannelName ? 'settings-disabled-area' : ''}><TeamSection title="Notifications">{choices.map(([key,label]) => <ToggleRow key={key} title={label} checked={settings.slackNotifications[key] ?? false} onChange={value => save({ slackNotifications: { ...settings.slackNotifications, [key]: value } })}/>)}</TeamSection></div></>
}

function RecurringIssuesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const issues = data.issues.filter(issue => issue.team.id === team.id && issue.recurrence)
  const [creating, setCreating] = useState(false); const [title, setTitle] = useState(''); const [cadence, setCadence] = useState<'daily'|'weekly'|'monthly'>('weekly')
  const create = async () => { if (!title.trim()) return; try { const issue = await createIssue({ title: title.trim(), description: '', teamId: team.id }); await updateIssue(issue.id, { recurrence: cadence }); setCreating(false); setTitle(''); await onReload() } catch (error) { toast.error(message(error)) } }
  return <TeamSection title="Recurring issues" action={<button className="settings-action" onClick={() => setCreating(true)}><Plus size={13}/>New recurring issue</button>}><div className="team-setting-list">{creating && <form className="recurring-issue-create" onSubmit={event => { event.preventDefault(); void create() }}><input autoFocus className="settings-input" placeholder="Issue title" value={title} onChange={event => setTitle(event.target.value)}/><select className="settings-select native" value={cadence} onChange={event => setCadence(event.target.value as typeof cadence)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select><button type="button" className="settings-icon-action" aria-label="Cancel" onClick={() => setCreating(false)}><X size={14}/></button><button className="settings-action primary" disabled={!title.trim()}>Create</button></form>}{issues.map(issue => <div className="recurring-issue-row" key={issue.id}><span><strong>{issue.identifier} {issue.title}</strong><small>{titleCase(issue.recurrence ?? '')}{issue.nextOccurrenceAt ? ` · Next ${new Date(issue.nextOccurrenceAt).toLocaleDateString()}` : ''}</small></span><select aria-label={`${issue.title} cadence`} className="settings-select native" value={issue.recurrence} onChange={event => void updateIssue(issue.id, { recurrence: event.target.value as 'daily'|'weekly'|'monthly' }).then(onReload)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></div>)}{!issues.length && !creating && <TeamEmpty icon={<Circle size={22}/>} title="No recurring issues" description="Create issues that repeat on a daily, weekly, or monthly schedule."/>}</div></TeamSection>
}

function WorkflowSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  const states = statesForTeam(data, team.id); const stateOptions = ['', ...states.map(item => item.id)]; const stateLabels = { '': 'No action', ...Object.fromEntries(states.map(item => [item.id, item.name])) }
  const prRows = [['opened','PR opened'],['draft','PR marked as draft'],['ready','PR ready for review'],['merged','PR merged'],['closed','PR closed']] as const
  return <><TeamSection title="Pull request automations">{prRows.map(([key,label]) => <SelectRow key={key} title={label} value={settings.prAutomations[key] ?? ''} options={stateOptions} labels={stateLabels} onChange={value => save({ prAutomations: { ...settings.prAutomations, [key]: value } })}/>)}</TeamSection><TeamSection title="Issue automations"><ToggleRow title="Close parent issues when all sub-issues are closed" checked={settings.autoCloseParents} onChange={value => save({ autoCloseParents: value })}/><ToggleRow title="Close sub-issues when their parent is closed" checked={settings.autoCloseSubIssues} onChange={value => save({ autoCloseSubIssues: value })}/><ToggleRow title="Close stale issues automatically" checked={settings.autoCloseStale} onChange={value => save({ autoCloseStale: value })}/>{settings.autoCloseStale && <><NumberRow title="Stale after" description="Months without activity" value={settings.staleMonths} onCommit={value => save({ staleMonths: value })}/><SelectRow title="Move stale issues to" value={settings.staleStatusId ?? ''} options={stateOptions} labels={stateLabels} onChange={value => save({ staleStatusId: value })}/></>}</TeamSection><TeamSection title="Archive and ordering"><NumberRow title="Archive completed issues after" description="Months after completion" value={settings.autoArchiveMonths} onCommit={value => save({ autoArchiveMonths: value })}/><SelectRow title="Newly started statuses" value={settings.progressOrder} options={['first','last','noAction']} labels={{ first: 'Move to first position', last: 'Move to last position', noAction: 'Do not reorder' }} onChange={value => save({ progressOrder: value as TeamSettings['progressOrder'] })}/></TeamSection></>
}

function TriageSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  const responsibilities=data.triageResponsibilities.filter(item=>item.teamId===team.id),rules=data.triageRoutingRules.filter(item=>item.teamId===team.id).sort((a,b)=>a.position-b.position)
  const members=data.teamMembers.filter(item=>item.teamId===team.id).map(item=>data.users.find(user=>user.id===item.userId)).filter(Boolean) as BootstrapData['users']
  const[name,setName]=useState(''),[userId,setUserId]=useState(''),[ruleName,setRuleName]=useState(''),[responsibilityId,setResponsibilityId]=useState('')
  const addResponsibility=async()=>{if(!name.trim()||!userId)return;try{await createTriageResponsibility(team.id,{name:name.trim(),mode:'individual',userIds:[userId]});setName('');await onReload()}catch(error){toast.error(message(error))}}
  const addRule=async()=>{if(!ruleName.trim()||!responsibilityId)return;try{await createTriageRule(team.id,{name:ruleName.trim(),conditions:{},responsibilityId,labelIds:[]});setRuleName('');await onReload()}catch(error){toast.error(message(error))}}
  return <><TeamSection><ToggleRow title="Enable Triage" description="Route incoming issues through ordered responsibilities and rules." checked={settings.triageEnabled} onChange={value=>save({triageEnabled:value})}/></TeamSection><div className={!settings.triageEnabled?'settings-disabled-area':''}><TeamSection title="Triage behavior"><ToggleRow title="Require priority" checked={settings.triageRequirePriority} onChange={value=>save({triageRequirePriority:value})}/><SelectRow title="Fallback responsibility" value={settings.triageAction} options={['none','creator','teamOwner']} labels={{none:'No assignee',creator:'Issue creator',teamOwner:'Team owner'}} onChange={value=>save({triageAction:value})}/></TeamSection><TeamSection title="Responsibilities"><form className="workflow-rule-create" onSubmit={event=>{event.preventDefault();void addResponsibility()}}><input className="settings-input" placeholder="Responsibility name" value={name} onChange={event=>setName(event.target.value)}/><select className="settings-select native" value={userId} onChange={event=>setUserId(event.target.value)}><option value="">Choose member…</option>{members.map(user=><option key={user.id} value={user.id}>{user.displayName}</option>)}</select><button className="settings-action" disabled={!name.trim()||!userId}><Plus size={13}/>Add</button></form>{responsibilities.map(item=><div className="automation-rule-row" key={item.id}><span><strong>{item.name}</strong><small>{item.mode} · {item.userIds.map(id=>data.users.find(user=>user.id===id)?.displayName).filter(Boolean).join(', ')}</small></span><Menu onDelete={()=>void deleteTriageResponsibility(team.id,item.id).then(onReload).catch(error=>toast.error(message(error)))}/></div>)}</TeamSection><TeamSection title="Routing rules"><form className="workflow-rule-create" onSubmit={event=>{event.preventDefault();void addRule()}}><input className="settings-input" placeholder="Rule name" value={ruleName} onChange={event=>setRuleName(event.target.value)}/><select className="settings-select native" value={responsibilityId} onChange={event=>setResponsibilityId(event.target.value)}><option value="">Choose responsibility…</option>{responsibilities.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="settings-action" disabled={!ruleName.trim()||!responsibilityId}><Plus size={13}/>Add rule</button></form>{rules.map(rule=><div className="automation-rule-row" key={rule.id}><span><strong>{rule.name}</strong><small>All incoming issues → {responsibilities.find(item=>item.id===rule.responsibilityId)?.name}</small></span><Menu onDelete={()=>void deleteTriageRule(team.id,rule.id).then(onReload).catch(error=>toast.error(message(error)))}/></div>)}{!rules.length&&<TeamEmpty icon={<GitBranch size={22}/>} title="No routing rules" description="Rules are evaluated in order and the first match owns the issue."/>}</TeamSection></div></>
}

function TeamAgentsSettings({ data }: { data: BootstrapData }) {
  const agents = data.integrationConnections.filter(item => /agent|copilot|cursor|github/i.test(`${item.provider} ${item.name}`) && item.status === 'connected')
  return <TeamSection title="Connected agents">{agents.map(item => <TeamRow key={item.id} title={item.name} description={item.provider}><span className="settings-static">Connected</span></TeamRow>)}{!agents.length && <TeamEmpty icon={<Bot size={24}/>} title="No team agents" description="Agent integrations connected at workspace level will appear here."/>}</TeamSection>
}

function AgentSkillsSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [instructions, setInstructions] = useState('')
  const add = async () => { if (!name.trim() || !instructions.trim()) return; await save({ agentSkills: [...settings.agentSkills, { id: `skill_${Date.now()}`, name: name.trim(), instructions: instructions.trim(), enabled: true }] }); setName(''); setInstructions(''); setCreating(false) }
  return <TeamSection title="Agent skills" action={<button className="settings-action" onClick={() => setCreating(true)}><Plus size={13}/>New skill</button>}><div className="team-setting-list">{creating && <form className="agent-skill-editor" onSubmit={event => { event.preventDefault(); void add() }}><input autoFocus className="settings-input" placeholder="Skill name" value={name} onChange={event => setName(event.target.value)}/><textarea className="settings-textarea" placeholder="Instructions" value={instructions} onChange={event => setInstructions(event.target.value)}/><footer><button type="button" className="settings-action" onClick={() => setCreating(false)}>Cancel</button><button className="settings-action primary" disabled={!name.trim() || !instructions.trim()}>Create</button></footer></form>}{settings.agentSkills.map(skill => <div className="agent-skill-row" key={skill.id}><WandSparkles size={17}/><span><strong>{skill.name}</strong><small>{skill.instructions}</small></span><SettingsToggle checked={skill.enabled} label={`${skill.name} enabled`} onChange={enabled => save({ agentSkills: settings.agentSkills.map(item => item.id === skill.id ? { ...item, enabled } : item) })}/><Menu onDelete={() => void save({ agentSkills: settings.agentSkills.filter(item => item.id !== skill.id) })}/></div>)}{!settings.agentSkills.length && !creating && <TeamEmpty icon={<Sparkles size={24}/>} title="No agent skills" description="Add reusable instructions for agents working with this team."/>}</div></TeamSection>
}

function ProjectUpdatePromptSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, setSettings, save } = useTeamSettings(data, team, onReload)
  return <TeamSection title="Project update prompt"><div className="team-prompt-editor"><p>Guidance used when generating project updates for {team.name}.</p><textarea aria-label="Project update prompt" value={settings.projectUpdatePrompt} onChange={event => setSettings({ ...settings, projectUpdatePrompt: event.target.value })} onBlur={() => void save({ projectUpdatePrompt: settings.projectUpdatePrompt })}/><span>{settings.projectUpdatePrompt.length} characters</span></div></TeamSection>
}

function ResolvedSummariesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const { settings, save } = useTeamSettings(data, team, onReload)
  return <TeamSection><ToggleRow title="Resolved thread summaries" description="Generate a concise summary when a project comment thread is resolved." checked={settings.resolvedThreadSummaries} onChange={value => save({ resolvedThreadSummaries: value })}/></TeamSection>
}

function MembersSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const memberships = new Map(data.teamMembers.filter(item => item.teamId === team.id).map(item => [item.userId, item]))
  const change = async (userId: string, member: boolean) => { try { await setTeamMembership(data.workspace.urlKey, team.id, userId, member, memberships.get(userId)?.role ?? 'member'); await onReload() } catch (error) { toast.error(message(error)) } }
  return <TeamSection title="Team members"><div className="team-setting-list">{data.members.filter(item => item.status === 'active').map(member => <div className="team-member-setting" key={member.user.id}><span className="settings-member-avatar">{initials(member.user.displayName)}</span><span><strong>{member.user.displayName}</strong><small>{member.user.email}</small></span>{memberships.get(member.user.id)?.role === 'owner' && <em>Owner</em>}<button role="checkbox" aria-checked={memberships.has(member.user.id)} onClick={() => void change(member.user.id, !memberships.has(member.user.id))}>{memberships.has(member.user.id) && <CheckboxMark/>}</button></div>)}</div></TeamSection>
}

function LabelsSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const labels = data.labels.filter(label => label.scope === team.id && !label.archivedAt); const [creating, setCreating] = useState(false)
  const add = async (name: string, color: string) => { try { await createTeamLabel(team.id, { name, color }); setCreating(false); await onReload() } catch (error) { toast.error(message(error)) } }
  return <TeamSection title="Issue labels" action={<button className="settings-action" onClick={() => setCreating(true)}><Plus size={13}/>New label</button>}><div className="team-setting-list">{creating && <InlineCreate placeholder="Label name" onCancel={() => setCreating(false)} onCreate={add}/>} {labels.map(label => <TeamLabelRow key={label.id} team={team} label={label} onReload={onReload}/>)} {!labels.length && !creating && <TeamEmpty icon={<Circle size={22}/>} title="No team labels" description="Team labels are available only on issues in this team."/>}</div></TeamSection>
}
function TeamLabelRow({ team, label, onReload }: { team: Team; label: IssueLabel; onReload: () => Promise<void> }) { const [name, setName] = useState(label.name); return <div className="team-label-setting"><input type="color" value={label.color} aria-label={`${label.name} color`} onChange={event => void updateTeamLabel(team.id, label.id, { color: event.target.value }).then(onReload)}/><input value={name} onChange={event => setName(event.target.value)} onBlur={() => name !== label.name && void updateTeamLabel(team.id, label.id, { name }).then(onReload)}/><span>{label.description || 'No description'}</span><Menu onDelete={() => void deleteTeamLabel(team.id, label.id).then(onReload)}/></div> }

function TemplatesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const [type,setType]=useState<'issue'|'project'|'document'>('issue');const[editing,setEditing]=useState<IssueTemplate|ProjectTemplate|DocumentTemplate|null|undefined>(undefined)
  const templates=type==='issue'?data.issueTemplates.filter(item=>item.teamId===team.id):type==='project'?data.projectTemplates.filter(item=>item.visibility==='teams'&&item.teamIds.includes(team.id)):data.documentTemplates.filter(item=>item.teamId===team.id)
  return <><div className="settings-segmented team-template-tabs">{(['issue','project','document'] as const).map(value=><button key={value} className={type===value?'active':''} onClick={()=>{setType(value);setEditing(undefined)}}>{`${titleCase(value)} templates`}</button>)}</div><TeamSection title={`${titleCase(type)} templates`} action={<button className="settings-action" onClick={()=>setEditing(null)}><Plus size={13}/>New template</button>}><div className="team-setting-list">{templates.map(template=><button className="team-template-setting" key={template.id} onClick={()=>setEditing(template)}><span className="template-icon">T</span><span><strong>{template.name}</strong><small>{template.description||`${titleCase(type)} template`}</small></span></button>)}{!templates.length&&<TeamEmpty icon={<Plus size={22}/>} title={`No ${type} templates`} description={`Templates prefill common ${type} properties and descriptions.`}/>}</div></TeamSection>{editing!==undefined&&(type==='document'?<DocumentTemplateEditor team={team} template={editing as DocumentTemplate|null} onClose={()=>setEditing(undefined)} onSaved={onReload}/>:<TemplateEditor data={data} type={type} teamId={team.id} template={editing as IssueTemplate|ProjectTemplate|null} onClose={()=>setEditing(undefined)} onSaved={onReload}/>)}</>
}

function DocumentTemplateEditor({team,template,onClose,onSaved}:{team:Team;template:DocumentTemplate|null;onClose:()=>void;onSaved:()=>Promise<void>}){const[name,setName]=useState(template?.name??'');const[description,setDescription]=useState(template?.description??'');const[documentTitle,setDocumentTitle]=useState(template?.title??'');const[content,setContent]=useState(template?.content??'');const[saving,setSaving]=useState(false);const save=async()=>{setSaving(true);try{const input={teamId:team.id,name,description,title:documentTitle,content};if(template)await updateDocumentTemplate(template.id,input);else await createDocumentTemplate(input);await onSaved();onClose()}catch(error){toast.error(message(error))}finally{setSaving(false)}};const remove=async()=>{if(!template)return;try{await deleteDocumentTemplate(template.id);await onSaved();onClose()}catch(error){toast.error(message(error))}};return <div className="template-full-editor"><header><button onClick={onClose}>Cancel</button><strong>{template?'Edit':'New'} document template</strong><button className="primary" disabled={!name.trim()||saving} onClick={()=>void save()}>{saving?'Saving…':'Save'}</button></header><div className="template-editor-content"><label>Template name<input autoFocus value={name} onChange={event=>setName(event.target.value)}/></label><label>Template description<input value={description} onChange={event=>setDescription(event.target.value)}/></label><label>Document title<input value={documentTitle} onChange={event=>setDocumentTitle(event.target.value)}/></label><label>Document content<textarea rows={14} value={content} onChange={event=>setContent(event.target.value)}/></label>{template&&<button className="settings-action danger" onClick={()=>void remove()}><Trash2 size={14}/>Delete template</button>}</div></div>}

function StatusesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const [states, setStates] = useState<WorkflowState[]>(statesForTeam(data, team.id)); const [createType, setCreateType] = useState<WorkflowStateType|null>(null); const [dragging, setDragging] = useState<string|null>(null)
  useEffect(() => { void fetchWorkflowStates(team.id).then(setStates).catch(() => setStates(statesForTeam(data, team.id))) }, [data, team.id])
  const reload = async () => { setStates(await fetchWorkflowStates(team.id)); await onReload() }
  const add = async (name: string, color: string) => { if (!createType) return; try { await createWorkflowState(team.id, { name, color, type: createType }); setCreateType(null); await reload() } catch (error) { toast.error(message(error)) } }
  const drop = async (target: string) => { if (!dragging || dragging === target) return; const next = [...states]; const from = next.findIndex(item => item.id === dragging); const to = next.findIndex(item => item.id === target); const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setStates(next); setDragging(null); try { setStates(await reorderWorkflowStates(team.id, next.map(item => item.id))); await onReload() } catch (error) { toast.error(message(error)); setStates(states) } }
  return <>{STATUS_GROUPS.map(group => <TeamSection key={group.label} title={group.label} action={!group.reserved && <button className="settings-icon-action" aria-label={`Add ${group.label} status`} onClick={() => setCreateType(group.type)}><Plus size={14}/></button>}><div className="workflow-state-list">{states.filter(item => item.type === group.type && Boolean(item.reserved) === Boolean(group.reserved)).map(state => <TeamStatusRow key={state.id} team={team} state={state} onDragStart={() => setDragging(state.id)} onDrop={() => void drop(state.id)} onReload={reload}/>)}{!group.reserved && createType === group.type && <InlineCreate placeholder="Status name" onCancel={() => setCreateType(null)} onCreate={add}/>}</div></TeamSection>)}</>
}
function TeamStatusRow({ team, state, onDragStart, onDrop, onReload }: { team: Team; state: WorkflowState; onDragStart: () => void; onDrop: () => void; onReload: () => Promise<void> }) { const [name, setName] = useState(state.name); const [description, setDescription] = useState(state.description ?? ''); const save = (patch: Partial<WorkflowState>) => updateWorkflowState(team.id, state.id, patch).then(onReload).catch(error => toast.error(message(error))); return <div className="workflow-state-row" draggable={!state.reserved} onDragStart={onDragStart} onDragOver={event => event.preventDefault()} onDrop={onDrop}><GripVertical size={14}/><input type="color" value={state.color} aria-label={`${state.name} color`} onChange={event => void save({ color: event.target.value })}/><span><input value={name} disabled={state.reserved} onChange={event => setName(event.target.value)} onBlur={() => name !== state.name && void save({ name })}/><input value={description} placeholder="Description" onChange={event => setDescription(event.target.value)} onBlur={() => description !== (state.description ?? '') && void save({ description })}/></span>{state.default && <em>Default</em>}{state.reserved ? <em>Reserved</em> : <Menu onDelete={() => void deleteWorkflowState(team.id, state.id).then(onReload).catch(error => toast.error(message(error)))}/>}</div> }

function CyclesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const initial = data.cycleSettings[team.id] ?? defaultCycles(); const [settings, setSettings] = useState(initial)
  useEffect(() => setSettings(data.cycleSettings[team.id] ?? defaultCycles()), [data.cycleSettings, team.id])
  const save = async (patch: Partial<CycleSettings>) => { const optimistic = { ...settings, ...patch }; setSettings(optimistic); try { setSettings(await updateCycleSettings(team.id, patch)); await onReload() } catch (error) { setSettings(settings); toast.error(message(error)) } }
  return <><TeamSection><ToggleRow title="Enable cycles" description="Organize work into time-boxed periods." checked={settings.enabled} onChange={value => save({ enabled: value })}/></TeamSection><div className={!settings.enabled ? 'settings-disabled-area' : ''}><TeamSection title="Schedule"><SelectRow title="Cycle duration" value={String(settings.durationWeeks)} options={['1','2','3','4','6','8']} labels={Object.fromEntries(['1','2','3','4','6','8'].map(value => [value, `${value} week${value === '1' ? '' : 's'}`]))} onChange={value => save({ durationWeeks: Number(value) })}/><SelectRow title="Cooldown" value={String(settings.cooldownWeeks)} options={['0','1','2','3','4']} labels={Object.fromEntries(['0','1','2','3','4'].map(value => [value, value === '0' ? 'No cooldown' : `${value} week${value === '1' ? '' : 's'}`]))} onChange={value => save({ cooldownWeeks: Number(value) })}/><NumberRow title="Capacity" description="Planning capacity shown on each generated cycle." value={settings.capacity} onCommit={value => save({ capacity: value })}/><NumberRow title="Upcoming cycles" value={settings.upcomingCount} onCommit={value => save({ upcomingCount: value })}/></TeamSection><TeamSection title="Automations"><ToggleRow title="Automatically create upcoming cycles" checked={settings.autoCreate} onChange={value => save({ autoCreate: value })}/><ToggleRow title="Add active issues" checked={settings.autoAddActive} onChange={value => save({ autoAddActive: value })}/><ToggleRow title="Add issues with due dates in the cycle" checked={settings.autoAddDueDate} onChange={value => save({ autoAddDueDate: value })}/><ToggleRow title="Add started issues" checked={settings.autoAddStarted} onChange={value => save({ autoAddStarted: value })}/><ToggleRow title="Add completed issues" checked={settings.autoAddCompleted} onChange={value => save({ autoAddCompleted: value })}/><ToggleRow title="Move unfinished issues to the next cycle" checked={settings.autoMigrate} onChange={value => save({ autoMigrate: value })}/></TeamSection></div></>
}

function TeamSection({ title, action, children }: { title?: string; action?: React.ReactNode; children: React.ReactNode }) { return <SettingsSection action={action} headerClassName="team-settings-section-title" title={title}>{children}</SettingsSection> }
function TeamRow(props: React.ComponentProps<typeof SettingsRow>) { return <SettingsRow {...props}/> }
function InputRow({ title, description, value, onChange, onCommit }: { title: string; description?: string; value: string; onChange: (value: string) => void; onCommit: (value: string) => void|Promise<void> }) { return <TeamRow title={title} description={description}><input className="settings-input" value={value} onChange={event => onChange(event.target.value)} onBlur={() => void onCommit(value)}/></TeamRow> }
function SelectRow({ title, description, value, options, labels = {}, onChange }: { title: string; description?: string; value: string; options: string[]; labels?: Record<string,string>; onChange: (value: string) => void|Promise<void> }) { return <TeamRow title={title} description={description}><select className="settings-select native" value={value} onChange={event => void onChange(event.target.value)}>{options.map(option => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></TeamRow> }
function ToggleRow({ title, description, checked, onChange }: { title: string; description?: string; checked: boolean; onChange: (value: boolean) => void|Promise<void> }) { return <TeamRow title={title} description={description}><SettingsToggle checked={checked} label={title} onChange={onChange}/></TeamRow> }
function NumberRow({ title, description, value, onCommit }: { title: string; description?: string; value: number; onCommit: (value: number) => void|Promise<void> }) { const [draft, setDraft] = useState(String(value)); useEffect(() => setDraft(String(value)), [value]); return <TeamRow title={title} description={description}><input type="number" min={0} className="settings-input short" value={draft} onChange={event => setDraft(event.target.value)} onBlur={() => void onCommit(Number(draft))}/></TeamRow> }
function InlineCreate({ placeholder, onCancel, onCreate }: { placeholder: string; onCancel: () => void; onCreate: (name: string, color: string) => void|Promise<void> }) { const [name, setName] = useState(''); const [color, setColor] = useState('#5E6AD2'); return <form className="workflow-inline-create" onSubmit={event => { event.preventDefault(); if (name.trim()) void onCreate(name.trim(), color) }}><input type="color" value={color} onChange={event => setColor(event.target.value)}/><input autoFocus placeholder={placeholder} value={name} onChange={event => setName(event.target.value)}/><button type="button" aria-label="Cancel" onClick={onCancel}><X size={14}/></button><button className="create" disabled={!name.trim()}><Check size={14}/></button></form> }
function Menu({ onDelete }: { onDelete: () => void }) { return <DropdownMenu><DropdownMenuTrigger asChild><button className="settings-icon-action" aria-label="More actions"><MoreHorizontal size={15}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem className="danger-item" onSelect={onDelete}><Trash2 size={14}/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu> }
function TeamEmpty({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div className="settings-empty compact">{icon}<h3>{title}</h3><p>{description}</p></div> }
function statesForTeam(data: BootstrapData, teamId: string) { const specific = data.states.some(state => state.teamId === teamId); return data.states.filter(state => specific ? state.teamId === teamId : !state.teamId).sort((a,b) => a.position-b.position) }
function defaultTeamSettings(teamId: string, states: WorkflowState[]): TeamSettings { return {
  teamId, timezone: 'Etc/UTC', estimateType: 'notUsed', defaultStateId: states.find(state => state.default)?.id ?? states[0]?.id ?? '', defaultPriority: 0, issueEmailEnabled: false, detailedHistory: false,
  access: 'public', membershipRestriction: 'open', settingsPermission: 'allMembers', labelPermission: 'allMembers', templatePermission: 'allMembers', agentSkillPermission: 'allMembers', loopPermission: 'allMembers', memberPermission: 'allMembers',
  slackNotifications: {}, prAutomations: {}, autoCloseParents: false, autoCloseSubIssues: false, autoCloseStale: false, staleMonths: 6, autoArchiveMonths: 6, progressOrder: 'first', releaseAutomations: [],
  triageEnabled: false, triageRequirePriority: false, triageAction: 'none', triageRules: [], agentSkills: [], projectUpdatePrompt: '', resolvedThreadSummaries: true, showInitiatives: true,
} }
function defaultCycles(): CycleSettings { return { enabled: false, durationWeeks: 2, cooldownWeeks: 0, startsOn: 1, upcomingCount: 2, capacity: 4, autoCreate: true, autoAddActive: false, autoAddDueDate: false, autoAddStarted: false, autoAddCompleted: false, autoMigrate: true, favoriteView: false } }
function initials(value: string) { return value.split(/\s+/).map(part => part[0]).join('').slice(0,2).toUpperCase() }
function message(error: unknown) { return error instanceof Error ? error.message : 'Could not save team settings' }
function titleCase(value:string){return value.slice(0,1).toUpperCase()+value.slice(1)}
