import { useEffect, useState } from 'react'
import { Check, Circle, GripVertical, MoreHorizontal, Plus, Trash2, X } from 'lucide-react'
import { toast } from 'sonner'

import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import {
  createDocumentTemplate, createTeamLabel, createWorkflowState, deleteDocumentTemplate, deleteTeamLabel, deleteWorkflowState,
  fetchWorkflowStates, reorderWorkflowStates, setTeamMembership, updateCycleSettings,
  updateDocumentTemplate, updateStructuredTeamSettings, updateTeam, updateTeamLabel, updateWorkflowState,
} from '@/lib/api'
import type { BootstrapData, CycleSettings, DocumentTemplate, IssueLabel, IssueTemplate, ProjectTemplate, Team, TeamSettings, WorkflowState, WorkflowStateType } from '@/types/flow'
import type { TeamSettingsSection } from '@/lib/app-routes'
import { TemplateEditor } from './advanced-settings'

const SECTIONS: { id: TeamSettingsSection; label: string }[] = [
  { id: 'general', label: 'General' }, { id: 'members', label: 'Members' }, { id: 'labels', label: 'Issue labels' },
  { id: 'templates', label: 'Templates' }, { id: 'statuses', label: 'Issue statuses' }, { id: 'cycles', label: 'Cycles' },
]
const STATUS_GROUPS: { type: WorkflowStateType; label: string; reserved?: boolean }[] = [
  { type: 'backlog', label: 'Backlog' }, { type: 'unstarted', label: 'Unstarted' }, { type: 'started', label: 'Started' }, { type: 'completed', label: 'Completed' }, { type: 'canceled', label: 'Canceled' }, { type: 'canceled', label: 'Duplicate', reserved: true },
]

export function TeamWorkflowSettings({ data, team, section, onNavigate, onReload }: { data: BootstrapData; team: Team; section: TeamSettingsSection; onNavigate: (section: TeamSettingsSection) => void; onReload: () => Promise<void> }) {
  return <>
    <header className="settings-page-header team-settings-header"><div><span className="settings-team-icon large" style={{ color: team.color }}>{team.icon || team.key[0]}</span><h1>{team.name}</h1></div></header>
    <nav className="team-settings-tabs" aria-label={`${team.name} settings`}>{SECTIONS.map(item => <button key={item.id} className={section === item.id ? 'active' : ''} onClick={() => onNavigate(item.id)}>{item.label}</button>)}</nav>
    {section === 'general' && <GeneralSettings data={data} team={team} onReload={onReload}/>} 
    {section === 'members' && <MembersSettings data={data} team={team} onReload={onReload}/>} 
    {section === 'labels' && <LabelsSettings data={data} team={team} onReload={onReload}/>} 
    {section === 'templates' && <TemplatesSettings data={data} team={team} onReload={onReload}/>} 
    {section === 'statuses' && <StatusesSettings data={data} team={team} onReload={onReload}/>} 
    {section === 'cycles' && <CyclesSettings data={data} team={team} onReload={onReload}/>} 
  </>
}

function GeneralSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const initial = data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states)
  const [settings, setSettings] = useState(initial)
  const [name, setName] = useState(team.name); const [identifier, setIdentifier] = useState(team.key)
  useEffect(() => { setSettings(data.teamSettings?.[team.id] ?? defaultTeamSettings(team.id, data.states)); setName(team.name); setIdentifier(team.key) }, [data.states, data.teamSettings, team.id, team.key, team.name])
  const save = async (patch: Partial<TeamSettings> & { identifier?: string }) => { try { setSettings(await updateStructuredTeamSettings(team.id, patch)); await onReload(); toast.success('Team settings saved') } catch (error) { toast.error(message(error)) } }
  return <>
    <Section title="Icon & Name"><Row title="Team icon"><span className="settings-team-icon large" style={{ color: team.color }}>{team.icon || team.key[0]}</span></Row><InputRow title="Name" value={name} onChange={setName} onCommit={async value => { await updateTeam(data.workspace.urlKey, team.id, { name: value }); await onReload() }}/></Section>
    <Section title="General"><InputRow title="Identifier" description="Used as the prefix for new issue identifiers. Existing issue identifiers won't change." value={identifier} onChange={value => setIdentifier(value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 5))} onCommit={value => save({ identifier: value })}/><InputRow title="Description" value={settings.description ?? ''} onChange={value => setSettings(current => ({ ...current, description: value }))} onCommit={value => save({ description: value })}/><SelectRow title="Timezone" description="Used when scheduling cycles and team automations." value={settings.timezone} options={['Etc/UTC','Asia/Shanghai','America/Los_Angeles','Europe/London']} onChange={value => save({ timezone: value })}/></Section>
    <Section title="Issues"><SelectRow title="Issue estimation" value={settings.estimateType} options={['notUsed','exponential','fibonacci','flow']} labels={{ notUsed: 'Not used', exponential: 'Exponential', fibonacci: 'Fibonacci', flow: 'Flow' }} onChange={value => save({ estimateType: value as TeamSettings['estimateType'] })}/><SelectRow title="Default status" value={settings.defaultStateId} options={statesForTeam(data, team.id).map(state => state.id)} labels={Object.fromEntries(statesForTeam(data, team.id).map(state => [state.id, state.name]))} onChange={value => save({ defaultStateId: value })}/><SelectRow title="Default priority" value={String(settings.defaultPriority)} options={['0','4','3','2','1']} labels={{ '0': 'No priority', '4': 'Low', '3': 'Medium', '2': 'High', '1': 'Urgent' }} onChange={value => save({ defaultPriority: Number(value) })}/><ToggleRow title="Create issues by email" description="Accept new team issues at a generated email address." checked={settings.issueEmailEnabled} onChange={value => save({ issueEmailEnabled: value })}/><ToggleRow title="Detailed issue history" description="Keep a full record of issue property changes." checked={settings.detailedHistory} onChange={value => save({ detailedHistory: value })}/></Section>
  </>
}

function MembersSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const memberships = new Map(data.teamMembers.filter(item => item.teamId === team.id).map(item => [item.userId, item]))
  const change = async (userId: string, member: boolean) => { try { await setTeamMembership(data.workspace.urlKey, team.id, userId, member, memberships.get(userId)?.role ?? 'member'); await onReload() } catch (error) { toast.error(message(error)) } }
  return <Section title="Team members"><div className="team-setting-list">{data.members.filter(item => item.status === 'active').map(member => <div className="team-member-setting" key={member.user.id}><span className="settings-member-avatar">{initials(member.user.displayName)}</span><span><strong>{member.user.displayName}</strong><small>{member.user.email}</small></span>{memberships.get(member.user.id)?.role === 'owner' && <em>Owner</em>}<button role="checkbox" aria-checked={memberships.has(member.user.id)} onClick={() => void change(member.user.id, !memberships.has(member.user.id))}>{memberships.has(member.user.id) && <Check size={13}/>}</button></div>)}</div></Section>
}

function LabelsSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const labels = data.labels.filter(label => label.scope === team.id && !label.archivedAt); const [creating, setCreating] = useState(false)
  const add = async (name: string, color: string) => { try { await createTeamLabel(team.id, { name, color }); setCreating(false); await onReload() } catch (error) { toast.error(message(error)) } }
  return <Section title="Issue labels" action={<button className="settings-action" onClick={() => setCreating(true)}><Plus size={13}/>New label</button>}><div className="team-setting-list">{creating && <InlineCreate placeholder="Label name" onCancel={() => setCreating(false)} onCreate={add}/>} {labels.map(label => <LabelRow key={label.id} team={team} label={label} onReload={onReload}/>)} {!labels.length && !creating && <Empty icon={<Circle size={22}/>} title="No team labels" description="Team labels are available only on issues in this team."/>}</div></Section>
}
function LabelRow({ team, label, onReload }: { team: Team; label: IssueLabel; onReload: () => Promise<void> }) { const [name, setName] = useState(label.name); return <div className="team-label-setting"><input type="color" value={label.color} aria-label={`${label.name} color`} onChange={event => void updateTeamLabel(team.id, label.id, { color: event.target.value }).then(onReload)}/><input value={name} onChange={event => setName(event.target.value)} onBlur={() => name !== label.name && void updateTeamLabel(team.id, label.id, { name }).then(onReload)}/><span>{label.description || 'No description'}</span><Menu onDelete={() => void deleteTeamLabel(team.id, label.id).then(onReload)}/></div> }

function TemplatesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const [type,setType]=useState<'issue'|'project'|'document'>('issue');const[editing,setEditing]=useState<IssueTemplate|ProjectTemplate|DocumentTemplate|null|undefined>(undefined)
  const templates=type==='issue'?data.issueTemplates.filter(item=>item.teamId===team.id):type==='project'?data.projectTemplates.filter(item=>item.visibility==='teams'&&item.teamIds.includes(team.id)):data.documentTemplates.filter(item=>item.teamId===team.id)
  return <><div className="settings-segmented team-template-tabs">{(['issue','project','document'] as const).map(value=><button key={value} className={type===value?'active':''} onClick={()=>{setType(value);setEditing(undefined)}}>{`${titleCase(value)} templates`}</button>)}</div><Section title={`${titleCase(type)} templates`} action={<button className="settings-action" onClick={()=>setEditing(null)}><Plus size={13}/>New template</button>}><div className="team-setting-list">{templates.map(template=><button className="team-template-setting" key={template.id} onClick={()=>setEditing(template)}><span className="template-icon">T</span><span><strong>{template.name}</strong><small>{template.description||`${titleCase(type)} template`}</small></span></button>)}{!templates.length&&<Empty icon={<Plus size={22}/>} title={`No ${type} templates`} description={`Templates prefill common ${type} properties and descriptions.`}/>}</div></Section>{editing!==undefined&&(type==='document'?<DocumentTemplateEditor team={team} template={editing as DocumentTemplate|null} onClose={()=>setEditing(undefined)} onSaved={onReload}/>:<TemplateEditor data={data} type={type} teamId={team.id} template={editing as IssueTemplate|ProjectTemplate|null} onClose={()=>setEditing(undefined)} onSaved={onReload}/>)}</>
}

function DocumentTemplateEditor({team,template,onClose,onSaved}:{team:Team;template:DocumentTemplate|null;onClose:()=>void;onSaved:()=>Promise<void>}){const[name,setName]=useState(template?.name??'');const[description,setDescription]=useState(template?.description??'');const[documentTitle,setDocumentTitle]=useState(template?.title??'');const[content,setContent]=useState(template?.content??'');const[saving,setSaving]=useState(false);const save=async()=>{setSaving(true);try{const input={teamId:team.id,name,description,title:documentTitle,content};if(template)await updateDocumentTemplate(template.id,input);else await createDocumentTemplate(input);await onSaved();onClose()}catch(error){toast.error(message(error))}finally{setSaving(false)}};const remove=async()=>{if(!template)return;try{await deleteDocumentTemplate(template.id);await onSaved();onClose()}catch(error){toast.error(message(error))}};return <div className="template-full-editor"><header><button onClick={onClose}>Cancel</button><strong>{template?'Edit':'New'} document template</strong><button className="primary" disabled={!name.trim()||saving} onClick={()=>void save()}>{saving?'Saving…':'Save'}</button></header><div className="template-editor-content"><label>Template name<input autoFocus value={name} onChange={event=>setName(event.target.value)}/></label><label>Template description<input value={description} onChange={event=>setDescription(event.target.value)}/></label><label>Document title<input value={documentTitle} onChange={event=>setDocumentTitle(event.target.value)}/></label><label>Document content<textarea rows={14} value={content} onChange={event=>setContent(event.target.value)}/></label>{template&&<button className="settings-action danger" onClick={()=>void remove()}><Trash2 size={14}/>Delete template</button>}</div></div>}

function StatusesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const [states, setStates] = useState<WorkflowState[]>(statesForTeam(data, team.id)); const [createType, setCreateType] = useState<WorkflowStateType|null>(null); const [dragging, setDragging] = useState<string|null>(null)
  useEffect(() => { void fetchWorkflowStates(team.id).then(setStates).catch(() => setStates(statesForTeam(data, team.id))) }, [data, team.id])
  const reload = async () => { setStates(await fetchWorkflowStates(team.id)); await onReload() }
  const add = async (name: string, color: string) => { if (!createType) return; try { await createWorkflowState(team.id, { name, color, type: createType }); setCreateType(null); await reload() } catch (error) { toast.error(message(error)) } }
  const drop = async (target: string) => { if (!dragging || dragging === target) return; const next = [...states]; const from = next.findIndex(item => item.id === dragging); const to = next.findIndex(item => item.id === target); const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setStates(next); setDragging(null); try { setStates(await reorderWorkflowStates(team.id, next.map(item => item.id))); await onReload() } catch (error) { toast.error(message(error)); setStates(states) } }
  return <>{STATUS_GROUPS.map(group => <Section key={group.label} title={group.label} action={!group.reserved && <button className="settings-icon-action" aria-label={`Add ${group.label} status`} onClick={() => setCreateType(group.type)}><Plus size={14}/></button>}><div className="workflow-state-list">{states.filter(item => item.type === group.type && Boolean(item.reserved) === Boolean(group.reserved)).map(state => <StatusRow key={state.id} team={team} state={state} onDragStart={() => setDragging(state.id)} onDrop={() => void drop(state.id)} onReload={reload}/>)}{!group.reserved && createType === group.type && <InlineCreate placeholder="Status name" onCancel={() => setCreateType(null)} onCreate={add}/>}</div></Section>)}</>
}
function StatusRow({ team, state, onDragStart, onDrop, onReload }: { team: Team; state: WorkflowState; onDragStart: () => void; onDrop: () => void; onReload: () => Promise<void> }) { const [name, setName] = useState(state.name); const [description, setDescription] = useState(state.description ?? ''); const save = (patch: Partial<WorkflowState>) => updateWorkflowState(team.id, state.id, patch).then(onReload).catch(error => toast.error(message(error))); return <div className="workflow-state-row" draggable={!state.reserved} onDragStart={onDragStart} onDragOver={event => event.preventDefault()} onDrop={onDrop}><GripVertical size={14}/><input type="color" value={state.color} aria-label={`${state.name} color`} onChange={event => void save({ color: event.target.value })}/><span><input value={name} disabled={state.reserved} onChange={event => setName(event.target.value)} onBlur={() => name !== state.name && void save({ name })}/><input value={description} placeholder="Description" onChange={event => setDescription(event.target.value)} onBlur={() => description !== (state.description ?? '') && void save({ description })}/></span>{state.default && <em>Default</em>}{state.reserved ? <em>Reserved</em> : <Menu onDelete={() => void deleteWorkflowState(team.id, state.id).then(onReload).catch(error => toast.error(message(error)))}/>}</div> }

function CyclesSettings({ data, team, onReload }: { data: BootstrapData; team: Team; onReload: () => Promise<void> }) {
  const initial = data.cycleSettings[team.id] ?? defaultCycles(); const [settings, setSettings] = useState(initial)
  useEffect(() => setSettings(data.cycleSettings[team.id] ?? defaultCycles()), [data.cycleSettings, team.id])
  const save = async (patch: Partial<CycleSettings>) => { const optimistic = { ...settings, ...patch }; setSettings(optimistic); try { setSettings(await updateCycleSettings(team.id, patch)); await onReload() } catch (error) { setSettings(settings); toast.error(message(error)) } }
  return <><Section><ToggleRow title="Enable cycles" description="Organize work into time-boxed periods." checked={settings.enabled} onChange={value => save({ enabled: value })}/></Section><div className={!settings.enabled ? 'settings-disabled-area' : ''}><Section title="Schedule"><SelectRow title="Cycle duration" value={String(settings.durationWeeks)} options={['1','2','3','4','6','8']} labels={Object.fromEntries(['1','2','3','4','6','8'].map(value => [value, `${value} week${value === '1' ? '' : 's'}`]))} onChange={value => save({ durationWeeks: Number(value) })}/><SelectRow title="Cooldown" value={String(settings.cooldownWeeks)} options={['0','1','2','3','4']} labels={Object.fromEntries(['0','1','2','3','4'].map(value => [value, value === '0' ? 'No cooldown' : `${value} week${value === '1' ? '' : 's'}`]))} onChange={value => save({ cooldownWeeks: Number(value) })}/><NumberRow title="Capacity" description="Planning capacity shown on each generated cycle." value={settings.capacity} onCommit={value => save({ capacity: value })}/><NumberRow title="Upcoming cycles" value={settings.upcomingCount} onCommit={value => save({ upcomingCount: value })}/></Section><Section title="Automations"><ToggleRow title="Automatically create upcoming cycles" checked={settings.autoCreate} onChange={value => save({ autoCreate: value })}/><ToggleRow title="Add active issues" checked={settings.autoAddActive} onChange={value => save({ autoAddActive: value })}/><ToggleRow title="Add issues with due dates in the cycle" checked={settings.autoAddDueDate} onChange={value => save({ autoAddDueDate: value })}/><ToggleRow title="Add started issues" checked={settings.autoAddStarted} onChange={value => save({ autoAddStarted: value })}/><ToggleRow title="Add completed issues" checked={settings.autoAddCompleted} onChange={value => save({ autoAddCompleted: value })}/><ToggleRow title="Move unfinished issues to the next cycle" checked={settings.autoMigrate} onChange={value => save({ autoMigrate: value })}/></Section></div></>
}

function Section({ title, action, children }: { title?: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="settings-section">{(title || action) && <header className="team-settings-section-title"><h3>{title}</h3>{action}</header>}<div className="settings-card">{children}</div></section> }
function Row({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <div className="settings-row"><div><strong>{title}</strong>{description && <span>{description}</span>}</div><div className="settings-control">{children}</div></div> }
function InputRow({ title, description, value, onChange, onCommit }: { title: string; description?: string; value: string; onChange: (value: string) => void; onCommit: (value: string) => void|Promise<void> }) { return <Row title={title} description={description}><input className="settings-input" value={value} onChange={event => onChange(event.target.value)} onBlur={() => void onCommit(value)}/></Row> }
function SelectRow({ title, description, value, options, labels = {}, onChange }: { title: string; description?: string; value: string; options: string[]; labels?: Record<string,string>; onChange: (value: string) => void|Promise<void> }) { return <Row title={title} description={description}><select className="settings-select native" value={value} onChange={event => void onChange(event.target.value)}>{options.map(option => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></Row> }
function ToggleRow({ title, description, checked, onChange }: { title: string; description?: string; checked: boolean; onChange: (value: boolean) => void|Promise<void> }) { return <Row title={title} description={description}><button className="settings-toggle" role="switch" aria-checked={checked} onClick={() => void onChange(!checked)}><span/></button></Row> }
function NumberRow({ title, description, value, onCommit }: { title: string; description?: string; value: number; onCommit: (value: number) => void|Promise<void> }) { const [draft, setDraft] = useState(String(value)); useEffect(() => setDraft(String(value)), [value]); return <Row title={title} description={description}><input type="number" min={0} className="settings-input short" value={draft} onChange={event => setDraft(event.target.value)} onBlur={() => void onCommit(Number(draft))}/></Row> }
function InlineCreate({ placeholder, onCancel, onCreate }: { placeholder: string; onCancel: () => void; onCreate: (name: string, color: string) => void|Promise<void> }) { const [name, setName] = useState(''); const [color, setColor] = useState('#5E6AD2'); return <form className="workflow-inline-create" onSubmit={event => { event.preventDefault(); if (name.trim()) void onCreate(name.trim(), color) }}><input type="color" value={color} onChange={event => setColor(event.target.value)}/><input autoFocus placeholder={placeholder} value={name} onChange={event => setName(event.target.value)}/><button type="button" aria-label="Cancel" onClick={onCancel}><X size={14}/></button><button className="create" disabled={!name.trim()}><Check size={14}/></button></form> }
function Menu({ onDelete }: { onDelete: () => void }) { return <DropdownMenu><DropdownMenuTrigger asChild><button className="settings-icon-action" aria-label="More actions"><MoreHorizontal size={15}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem className="danger-item" onSelect={onDelete}><Trash2 size={14}/>Delete</DropdownMenuItem></DropdownMenuContent></DropdownMenu> }
function Empty({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) { return <div className="settings-empty compact">{icon}<h3>{title}</h3><p>{description}</p></div> }
function statesForTeam(data: BootstrapData, teamId: string) { const specific = data.states.some(state => state.teamId === teamId); return data.states.filter(state => specific ? state.teamId === teamId : !state.teamId).sort((a,b) => a.position-b.position) }
function defaultTeamSettings(teamId: string, states: WorkflowState[]): TeamSettings { return { teamId, timezone: 'Etc/UTC', estimateType: 'notUsed', defaultStateId: states.find(state => state.default)?.id ?? states[0]?.id ?? '', defaultPriority: 0, issueEmailEnabled: false, detailedHistory: false } }
function defaultCycles(): CycleSettings { return { enabled: false, durationWeeks: 2, cooldownWeeks: 0, startsOn: 1, upcomingCount: 2, capacity: 4, autoCreate: true, autoAddActive: false, autoAddDueDate: false, autoAddStarted: false, autoAddCompleted: false, autoMigrate: true } }
function initials(value: string) { return value.split(/\s+/).map(part => part[0]).join('').slice(0,2).toUpperCase() }
function message(error: unknown) { return error instanceof Error ? error.message : 'Could not save team settings' }
function titleCase(value:string){return value.slice(0,1).toUpperCase()+value.slice(1)}
