import * as Popover from '@radix-ui/react-popover'
import { Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleDot, Copy, ExternalLink, FileCode2, Filter, GitBranch, GitMerge, GitPullRequest, Link2, MoreHorizontal, PanelRightClose, Plus, Search, Settings2, Sparkles, Star, Users, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { toast } from 'sonner'

import { Avatar } from '@/components/issue/issue-row'
import { usePropertyCommand } from '@/components/property/use-property-command'
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'
import { Toggle } from '@/components/ui/toggle'
import { CheckboxMark } from '@/components/ui/checkbox-mark'
import { useI18n } from '@/i18n/i18n'
import { commentOnReview, submitReview, updateReview } from '@/lib/api'
import { integrationSettingsPath, issuePath, reviewPath, reviewsPath, type ReviewRouteTab } from '@/lib/app-routes'
import type { BootstrapData, CodeReview } from '@/types/flow'

import './reviews-page.css'

type Display={grouping:'focus'|'status'|'repository';ordering:'importance'|'updated'|'opened';closed:'day'|'week'|'month'|'all';showDrafts:boolean;showTeams:boolean;badge:'all'|'requested';properties:string[]}
type FilterState={status?:string;query?:string;author?:string;reviewer?:string;repository?:string;quick?:boolean;missingIssue?:boolean}
const DEFAULT_DISPLAY:Display={grouping:'focus',ordering:'importance',closed:'day',showDrafts:true,showTeams:true,badge:'all',properties:['repository','author','opened','status','quick']}

export function ReviewsPage({data,view,review,tab='overview',onNavigate,onReload,onOpenSidebar}:{data:BootstrapData;view:'for-you'|'created';review?:CodeReview;tab?:ReviewRouteTab;onNavigate:(path:string)=>void;onReload:()=>Promise<void>;onOpenSidebar:()=>void}){
  const {t}=useI18n(),[filter,setFilter]=useState<FilterState>({}),[display,setDisplay]=useState(DEFAULT_DISPLAY)
  const [submitOpen,setSubmitOpen]=useState(false),[picker,setPicker]=useState<'reviewers'|'issues'|null>(null),[busy,setBusy]=useState(false)
  const visible=useMemo(()=>data.reviews.filter(item=>view==='created'?item.author.id===data.viewer.id:item.reviewerIds.includes(data.viewer.id)).filter(item=>display.showDrafts||!item.draft).filter(item=>filter.status?item.status===filter.status:true).filter(item=>filter.author?item.author.id===filter.author:true).filter(item=>filter.reviewer?item.reviewerIds.includes(filter.reviewer):true).filter(item=>filter.repository?`${item.repositoryOwner}/${item.repositoryName}`===filter.repository:true).filter(item=>filter.quick?item.quickToReview:true).filter(item=>filter.missingIssue?!item.issueIds.length:true).filter(item=>filter.query?`${item.title} ${item.repositoryOwner} ${item.repositoryName}`.toLowerCase().includes(filter.query.toLowerCase()):true).sort((a,b)=>display.ordering==='opened'?b.createdAt.localeCompare(a.createdAt):b.updatedAt.localeCompare(a.updatedAt)),[data.reviews,data.viewer.id,display,filter,view])
  const mutate=async(input:Parameters<typeof updateReview>[1])=>{if(!review)return;setBusy(true);try{await updateReview(review.id,input);await onReload()}catch(error){toast.error(error instanceof Error?error.message:t('Could not update review'))}finally{setBusy(false)}}
  return <main className={`reviews-workspace ${review?'has-detail':''}`}>
    <section className="reviews-list-pane"><header className="reviews-topbar"><button className="reviews-mobile-sidebar" aria-label={t('Open sidebar')} onClick={onOpenSidebar}><PanelRightClose/></button><h1>{t('Reviews')}</h1><div><ReviewFilterMenu filter={filter} data={data} onChange={setFilter}/><ReviewDisplayMenu display={display} onChange={setDisplay}/></div></header><nav className="reviews-tabs"><a className={view==='for-you'?'active':''} href={reviewsPath(data.workspace.urlKey)} onClick={event=>{event.preventDefault();onNavigate(reviewsPath(data.workspace.urlKey))}}>{t('For you')}</a><a className={view==='created'?'active':''} href={reviewsPath(data.workspace.urlKey,'created')} onClick={event=>{event.preventDefault();onNavigate(reviewsPath(data.workspace.urlKey,'created'))}}>{t('Created')}</a></nav>
      {visible.length
        ? <div className="review-groups"><button className="review-group-heading">{t(view==='created'?'Created by you':'Needs your review')}<ChevronDown/></button>{visible.map(item=><ReviewRow key={item.id} item={item} active={review?.id===item.id} data={data} onOpen={()=>onNavigate(reviewPath(data.workspace.urlKey,item))}/>)}</div>
        : <ReviewEmpty connected={data.integrationConnections.some(item=>item.provider==='github'||item.provider==='gitlab')} onConnect={provider=>onNavigate(integrationSettingsPath(data.workspace.urlKey,provider))}/>}
    </section>
    <section className="reviews-detail-pane">{review?<ReviewDetail data={data} review={review} tab={tab} busy={busy} onNavigate={onNavigate} onMutate={mutate} onReload={onReload} onOpenSubmit={()=>setSubmitOpen(true)} onOpenPicker={setPicker}/>:<div className="reviews-selection-empty"><GitPullRequest/><span>{visible.length} {t(visible.length===1?'review':'reviews')}</span></div>}</section>
    {review&&<SubmitReviewDialog open={submitOpen} busy={busy} review={review} onClose={()=>setSubmitOpen(false)} onSubmit={async(decision,body)=>{setBusy(true);try{await submitReview(review.id,{decision,body});await onReload();setSubmitOpen(false)}catch(error){toast.error(error instanceof Error?error.message:t('Could not submit review'))}finally{setBusy(false)}}}/>} {review&&picker&&<PeopleIssuePicker type={picker} data={data} review={review} onClose={()=>setPicker(null)} onSave={async ids=>{await mutate(picker==='reviewers'?{reviewerIds:ids}:{issueIds:ids});setPicker(null)}}/>}
  </main>
}

function ReviewRow({item,active,onOpen}:{item:CodeReview;active:boolean;data:BootstrapData;onOpen:()=>void}){const{t}=useI18n();const Provider=item.provider==='github'?GitPullRequest:GitMerge;return <button className={`review-row ${active?'active':''}`} onClick={onOpen}><Provider/><span data-i18n-ignore>{item.title}</span>{item.quickToReview&&<Sparkles aria-label={t('Quick to review')}/>}<small>{relative(item.updatedAt,t)}</small></button>}

function ReviewEmpty({connected,onConnect}:{connected:boolean;onConnect:(provider:'github'|'gitlab')=>void}){const{t}=useI18n();return <div className="reviews-empty"><GitPullRequest/><strong>{t(connected?'Nothing to review':'Connect a code host')}</strong><span>{t(connected?'Reviews assigned to you will appear here.':'Connect GitHub or GitLab to sync pull and merge requests.')}</span>{!connected&&<div><button onClick={()=>onConnect('github')}><GitPullRequest/>GitHub</button><button onClick={()=>onConnect('gitlab')}><GitMerge/>GitLab</button></div>}</div>}

function ReviewDetail({data,review,tab,busy,onNavigate,onMutate,onReload,onOpenSubmit,onOpenPicker}:{data:BootstrapData;review:CodeReview;tab:ReviewRouteTab;busy:boolean;onNavigate:(path:string)=>void;onMutate:(input:Parameters<typeof updateReview>[1])=>Promise<void>;onReload:()=>Promise<void>;onOpenSubmit:()=>void;onOpenPicker:(value:'reviewers'|'issues')=>void}){
  const{t}=useI18n(),[comment,setComment]=useState('');const issues=data.issues.filter(item=>review.issueIds.includes(item.id)),reviewers=data.users.filter(user=>review.reviewerIds.includes(user.id));const passed=review.checks.every(check=>check.status==='passed'||check.status==='skipped');const closed=review.status==='merged'||review.status==='closed'
  const commentSubmit=async()=>{if(!comment.trim())return;await commentOnReview(review.id,comment);setComment('');await onReload()}
  return <><header className="review-detail-top"><button className="review-mobile-back" aria-label={t('Back to reviews')} onClick={()=>onNavigate(reviewsPath(data.workspace.urlKey))}><ChevronLeft/></button><div>{issues[0]?<a href={issuePath(data.workspace.urlKey,issues[0])} onClick={event=>{event.preventDefault();onNavigate(issuePath(data.workspace.urlKey,issues[0]))}} data-i18n-ignore>{issues[0].identifier}</a>:<button onClick={()=>onOpenPicker('issues')}>{t('No issue')}</button>}<ChevronRight/><GitPullRequest/><strong data-i18n-ignore>#{review.number} {review.title}</strong></div><span className="review-diff-count"><b>+{review.additions}</b><i>-{review.deletions}</i></span><button aria-label={t(review.favorite?'Remove from favorites':'Add to favorites')} onClick={()=>void onMutate({favorite:!review.favorite})}><Star fill={review.favorite?'currentColor':'none'}/></button><ReviewActions review={review} onMutate={onMutate} onOpenPicker={onOpenPicker} onQuickApprove={async()=>{await submitReview(review.id,{decision:'approve',body:''});await onReload()}}/><a aria-label={t('Open in code host')} href={review.url} target="_blank" rel="noreferrer"><ExternalLink/></a></header><div className="review-detail-tabs"><nav>{(['overview','review','changes'] as const).map(value=><a className={tab===value?'active':''} key={value} href={reviewPath(data.workspace.urlKey,review,value)} onClick={event=>{event.preventDefault();onNavigate(reviewPath(data.workspace.urlKey,review,value))}}>{t(value==='overview'?'Overview':value==='review'?'Guide':'Diff')}</a>)}</nav><button disabled={busy||closed||!passed} onClick={()=>void onMutate({status:'merged'})}><GitMerge/>{t('Squash & merge')}</button><button className="review-submit" disabled={busy||closed} onClick={onOpenSubmit}>{t('Submit review')}</button></div>
    {tab==='overview'?<div className="review-overview"><h2 data-i18n-ignore>{review.title}</h2><div className="review-byline"><Avatar name={review.author.displayName}/><span data-i18n-ignore>{review.author.displayName}</span><b>·</b><a href={review.url} target="_blank" rel="noreferrer" data-i18n-ignore>{review.repositoryName}#{review.number}</a><b>·</b><code data-i18n-ignore>{review.baseBranch}</code><span>←</span><code data-i18n-ignore>{review.headBranch}</code></div><dl><dt>{t('Status')}</dt><dd><GitPullRequest/><button onClick={()=>void onMutate({draft:!review.draft})}>{t(review.draft?'Draft':statusLabel(review.status))}</button>{!closed&&<em>{t(review.status==='approved'?'Approved':'Waiting for your review')}</em>}</dd><dt>{t('Reviewers')}</dt><dd><button className="review-people" onClick={()=>onOpenPicker('reviewers')}>{reviewers.map(user=><Avatar key={user.id} name={user.displayName}/>)}<span>{reviewers.map(user=>user.displayName).join(', ')||t('Select reviewers')}</span></button><button className="review-add" aria-label={t('Add reviewer')} onClick={()=>onOpenPicker('reviewers')}><Plus/></button></dd><dt>{t('Checks')}</dt><dd><ChecksMenu checks={review.checks}/></dd><dt>{t('Branch')}</dt><dd><GitBranch/><button disabled={review.branchState==='upToDate'} onClick={()=>void onMutate({branchState:'upToDate'})}>{t(review.branchState==='upToDate'?'Up to date with main':review.branchState==='conflicted'?'Conflicts':'Behind main')}</button></dd><dt>{t('Issues')}</dt><dd className="review-issues">{issues.map(issue=><a data-i18n-ignore href={issuePath(data.workspace.urlKey,issue)} onClick={event=>{event.preventDefault();onNavigate(issuePath(data.workspace.urlKey,issue))}} key={issue.id}>{issue.identifier}</a>)}<button onClick={()=>onOpenPicker('issues')}><Plus/>{t(issues.length?'Change issues':'Link issue')}</button></dd></dl><section className="review-description"><h3>{t('Description')}</h3><p data-i18n-ignore>{review.description}</p></section><section className="review-activity"><h3>{t('Activity')}</h3>{review.events.map(event=><div key={event.id}><Avatar name={event.actor.displayName}/><p><strong data-i18n-ignore>{event.actor.displayName}</strong> {t(eventText(event.type))}{event.body&&<span data-i18n-ignore> {event.body}</span>}<small>{relative(event.createdAt,t)}</small></p></div>)}</section><div className="review-comment"><textarea aria-label={t('Leave a comment…')} placeholder={t('Leave a comment…')} value={comment} onChange={event=>setComment(event.target.value)}/><button disabled={!comment.trim()} onClick={()=>void commentSubmit()}>{t('Submit comment')}</button></div></div>:tab==='review'?<ReviewGuide review={review}/>:<ReviewChanges review={review}/>}</>
}

function ReviewFilterMenu({filter,data,onChange}:{filter:FilterState;data:BootstrapData;onChange:(value:FilterState)=>void}){
  const{t}=useI18n(),[open,setOpen]=useState(false),[view,setView]=useState<'fields'|'status'|'author'|'reviewer'|'repository'>('fields')
  const repositories=[...new Set(data.reviews.map(item=>`${item.repositoryOwner}/${item.repositoryName}`))]
  const users=view==='author'?data.users.filter(user=>data.reviews.some(item=>item.author.id===user.id)):data.users
  const options=view==='fields'?[{id:'status',label:'Status'},{id:'author',label:'Author'},{id:'reviewer',label:'Reviewers'},{id:'repository',label:'Repository name'},{id:'quick',label:'Quick to review'},{id:'missingIssue',label:'Missing issue'}]:view==='status'?['open','inReview','approved','merged','closed'].map(id=>({id,label:statusLabel(id)})):view==='repository'?repositories.map(id=>({id,label:id})):users.map(user=>({id:user.id,label:user.displayName,keywords:`${user.name} ${user.email}`}))
  const back=()=>{command.onQueryChange('');setView('fields')}
  const select=(key:keyof FilterState,value:string|boolean)=>{onChange({...filter,[key]:filter[key]===value?undefined:value});back()}
  const command=usePropertyCommand({closeOnSelect:false,open,options,resetKey:view,selectedIds:[],onOpenChange:setOpen,onSelect:option=>{if(view==='fields'){if(option.id==='quick'||option.id==='missingIssue')select(option.id,true);else setView(option.id as typeof view)}else{const key=view==='status'?'status':view==='author'?'author':view==='reviewer'?'reviewer':'repository';select(key,option.id)}}})
  return <Popover.Root open={open} onOpenChange={next=>{setOpen(next);if(!next)back()}}><Popover.Trigger asChild><button className="reviews-icon-button" aria-label={t('Add filter')}><Filter/></button></Popover.Trigger><Popover.Portal><Popover.Content className="reviews-command" align="end" sideOffset={5} onKeyDown={command.onKeyDown} onEscapeKeyDown={event=>{if(view!=='fields'){event.preventDefault();back()}}}><label>{view!=='fields'?<button aria-label={t('Back')} onClick={back}>‹</button>:<Search/>}<input ref={command.inputRef} key={view} autoFocus aria-label={t(view==='fields'?'Add Filter…':'Filter…')} placeholder={t(view==='fields'?'Add Filter…':'Filter…')} value={command.query} onChange={event=>command.onQueryChange(event.target.value)}/>{view==='fields'&&<kbd>F</kbd>}</label><div role="listbox">{command.filteredOptions.map(option=>{const selected=option.id==='quick'?filter.quick:option.id==='missingIssue'?filter.missingIssue:view==='fields'?false:filter[view]===option.id;return <button role="option" aria-selected={command.activeId===option.id} aria-checked={selected||undefined} key={option.id} onPointerMove={()=>command.setActiveId(option.id)} onFocus={()=>command.setActiveId(option.id)} onClick={()=>command.choose(option)}>{option.id==='quick'?<Sparkles/>:option.id==='missingIssue'?<Link2/>:<CircleDot/>}<span data-i18n-ignore={view!=='fields'&&view!=='status'||undefined}>{view==='status'||view==='fields'?t(option.label):option.label}</span>{view==='fields'&&option.id!=='quick'&&option.id!=='missingIssue'?<ChevronRight/>:selected?<Check/>:null}</button>})}</div></Popover.Content></Popover.Portal></Popover.Root>
}

function ReviewDisplayMenu({display,onChange}:{display:Display;onChange:(value:Display)=>void}){const{t}=useI18n();const toggle=(property:string)=>onChange({...display,properties:display.properties.includes(property)?display.properties.filter(item=>item!==property):[...display.properties,property]});return <Popover.Root><Popover.Trigger asChild><button className="reviews-icon-button" aria-label={t('Display options')}><Settings2/></button></Popover.Trigger><Popover.Portal><Popover.Content className="reviews-display" align="end" sideOffset={5}><SelectLine label={t('Grouping')} value={display.grouping} options={['focus','status','repository']} onChange={grouping=>onChange({...display,grouping:grouping as Display['grouping']})}/><SelectLine label={t('Ordering')} value={display.ordering} options={['importance','updated','opened']} onChange={ordering=>onChange({...display,ordering:ordering as Display['ordering']})}/><SelectLine label={t('Closed reviews')} value={display.closed} options={['day','week','month','all']} onChange={closed=>onChange({...display,closed:closed as Display['closed']})}/><CheckLine label={t('Show drafts')} checked={display.showDrafts} onChange={showDrafts=>onChange({...display,showDrafts})}/><CheckLine label={t('Show GitHub team reviews')} checked={display.showTeams} onChange={showTeams=>onChange({...display,showTeams})}/><h4>{t('Display properties')}</h4><div className="review-property-pills">{['repository','id','author','opened','status','quick'].map(value=><button aria-pressed={display.properties.includes(value)} key={value} onClick={()=>toggle(value)}>{t(value==='quick'?'Quick to review':value[0].toUpperCase()+value.slice(1))}</button>)}</div></Popover.Content></Popover.Portal></Popover.Root>}

function SelectLine({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){const{t}=useI18n();return <label className="review-select-line"><span>{label}</span><select aria-label={label} value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option} value={option}>{t(option[0].toUpperCase()+option.slice(1))}</option>)}</select></label>}
function CheckLine({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="review-check-line"><span>{label}</span><Toggle checked={checked} label={label} onChange={onChange}/></label>}

function ReviewActions({review,onMutate,onOpenPicker,onQuickApprove}:{review:CodeReview;onMutate:(input:Parameters<typeof updateReview>[1])=>Promise<void>;onOpenPicker:(value:'reviewers'|'issues')=>void;onQuickApprove:()=>Promise<void>}){const{t}=useI18n();const closed=review.status==='merged'||review.status==='closed';return <Popover.Root><Popover.Trigger asChild><button aria-label={t('Pull request actions')}><MoreHorizontal/></button></Popover.Trigger><Popover.Portal><Popover.Content className="review-actions-menu" align="end" sideOffset={5} onKeyDown={commandKeyDown}><a href={review.url} target="_blank" rel="noreferrer"><ExternalLink/>{t(`Open in ${review.provider==='github'?'GitHub':'GitLab'}`)}</a><button onClick={()=>void onMutate({favorite:!review.favorite})}><Star/>{t(review.favorite?'Unfavorite':'Favorite')}</button><hr/><button onClick={()=>void navigator.clipboard.writeText(location.href)}><Copy/>{t('Copy URL')}</button><button onClick={()=>void navigator.clipboard.writeText(review.headBranch)}><GitBranch/>{t('Copy branch name')}</button><hr/><button onClick={()=>onOpenPicker('issues')}><Link2/>{t('Link issue')}</button><button onClick={()=>onOpenPicker('reviewers')}><Users/>{t('Select reviewers')}</button><button disabled={closed} onClick={()=>void onQuickApprove()}><CheckCircle2/>{t('Quick approve')}</button><hr/>{closed?<button onClick={()=>void onMutate({status:'open'})}><GitPullRequest/>{t('Reopen pull request')}</button>:<><button onClick={()=>void onMutate({branchState:'upToDate'})}><GitBranch/>{t('Update branch')}</button><button onClick={()=>void onMutate({draft:!review.draft})}><GitPullRequest/>{t(review.draft?'Mark ready for review':'Convert to draft')}</button><button onClick={()=>void onMutate({status:'merged'})}><GitMerge/>{t('Merge pull request')}</button><button className="danger" onClick={()=>void onMutate({status:'closed'})}><X/>{t('Close pull request')}</button></>}</Popover.Content></Popover.Portal></Popover.Root>}

function ChecksMenu({checks}:{checks:CodeReview['checks']}){const{t}=useI18n();const passed=checks.every(item=>item.status==='passed'||item.status==='skipped');return <Popover.Root><Popover.Trigger asChild><button className={passed?'passed':'failed'}><CheckCircle2/>{t(passed?'All passed':'Checks need attention')}</button></Popover.Trigger><Popover.Portal><Popover.Content className="review-checks-menu" align="start" sideOffset={5}><h3>{t('Checks')}<span>{checks.length}</span></h3>{checks.map(check=><div key={check.id}><CheckCircle2 className={check.status}/><span data-i18n-ignore>{check.name}</span><small>{t(check.status)}</small></div>)}</Popover.Content></Popover.Portal></Popover.Root>}

function SubmitReviewDialog({open,busy,review,onClose,onSubmit}:{open:boolean;busy:boolean;review:CodeReview;onClose:()=>void;onSubmit:(decision:'approve'|'comment'|'requestChanges',body:string)=>Promise<void>}){const{t}=useI18n();const[decision,setDecision]=useState<'approve'|'comment'|'requestChanges'>('comment'),[body,setBody]=useState('');return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent className="submit-review-dialog" onInteractOutside={event=>event.preventDefault()} onPointerDownOutside={event=>event.preventDefault()}><DialogTitle>{t('Submit review')}</DialogTitle><p data-i18n-ignore>{review.title}</p><textarea autoFocus aria-label={t('Review summary')} placeholder={t('Leave a review summary…')} value={body} onChange={event=>setBody(event.target.value)}/><div role="radiogroup" aria-label={t('Review decision')}>{(['comment','approve','requestChanges'] as const).map(value=><button type="button" role="radio" aria-checked={decision===value} key={value} onClick={event=>{event.preventDefault();event.stopPropagation();setDecision(value)}}><span>{decision===value&&<i/>}</span>{t(value==='comment'?'Comment':value==='approve'?'Approve':'Request changes')}</button>)}</div><footer><button type="button" onClick={onClose}>{t('Cancel')}</button><button type="button" className="primary" disabled={busy} onClick={()=>void onSubmit(decision,body)}>{t('Submit review')}</button></footer></DialogContent></Dialog>}

function PeopleIssuePicker({type,data,review,onClose,onSave}:{type:'reviewers'|'issues';data:BootstrapData;review:CodeReview;onClose:()=>void;onSave:(ids:string[])=>Promise<void>}){const{t}=useI18n();const initial=type==='reviewers'?review.reviewerIds:review.issueIds,[selected,setSelected]=useState(initial),[busy,setBusy]=useState(false);const options=(type==='reviewers'?data.users.map(user=>({id:user.id,label:user.displayName,keywords:`${user.name} ${user.email}`})):data.issues.map(issue=>({id:issue.id,label:`${issue.identifier} ${issue.title}`})));const command=usePropertyCommand({closeOnSelect:false,open:true,options,selectedIds:selected,onOpenChange:open=>!open&&onClose(),onSelect:option=>setSelected(current=>current.includes(option.id)?current.filter(id=>id!==option.id):[...current,option.id])});return <Dialog open onOpenChange={value=>!value&&onClose()}><DialogContent className="review-picker-dialog" onInteractOutside={event=>event.preventDefault()} onPointerDownOutside={event=>event.preventDefault()}><DialogTitle>{t(type==='reviewers'?'Select reviewers':'Link issues')}</DialogTitle><label><Search/><input ref={command.inputRef} autoFocus aria-label={t('Filter…')} placeholder={t('Filter…')} value={command.query} onChange={event=>command.onQueryChange(event.target.value)} onKeyDown={command.onKeyDown}/></label><div role="listbox" aria-multiselectable onKeyDown={command.onKeyDown}>{command.filteredOptions.map(option=>{const checked=command.isSelected(option.id),user=type==='reviewers'?data.users.find(item=>item.id===option.id):undefined;return <button type="button" role="option" aria-selected={command.activeId===option.id} aria-checked={checked} key={option.id} onPointerMove={()=>command.setActiveId(option.id)} onFocus={()=>command.setActiveId(option.id)} onClick={event=>{event.preventDefault();event.stopPropagation();command.choose(option)}}><span role="checkbox" aria-checked={checked}>{checked&&<CheckboxMark/>}</span>{user?<><Avatar name={user.displayName}/><strong data-i18n-ignore>{user.displayName}</strong></>:<><GitPullRequest/><strong data-i18n-ignore>{option.label}</strong></>}</button>})}</div><footer><button type="button" onClick={onClose}>{t('Cancel')}</button><button type="button" className="primary" disabled={busy} onClick={()=>{setBusy(true);void onSave(selected).finally(()=>setBusy(false))}}>{t('Save')}</button></footer></DialogContent></Dialog>}

function ReviewGuide({review}:{review:CodeReview}){const{t}=useI18n();return <div className="review-guide"><Sparkles/><h2>{t('Review guide')}</h2><p>{t('Start with the highest-impact files, then confirm tests and issue scope.')}</p>{review.files.map((file,index)=><article key={file.path}><span>{index+1}</span><div><strong data-i18n-ignore>{file.path}</strong><p>{t(index===0?'Check interaction behavior and keyboard accessibility.':'Confirm regression coverage and failure states.')}</p></div></article>)}</div>}
function ReviewChanges({review}:{review:CodeReview}){const{t}=useI18n();return <div className="review-changes"><header><h2>{t('Files changed')}</h2><span>{review.files.length}</span></header>{review.files.map(file=><article key={file.path}><header><FileCode2/><strong data-i18n-ignore>{file.path}</strong><b>+{file.additions}</b><i>-{file.deletions}</i></header><pre data-i18n-ignore>{file.patch}</pre></article>)}</div>}
function statusLabel(status:string){return status==='inReview'?'In review':status[0].toUpperCase()+status.slice(1)}
function eventText(type:string){return type==='opened'?'opened the pull request':type==='review_requested'?'requested a review from':type==='approved'?'approved these changes':type==='changes_requested'?'requested changes':type==='commented'||type==='review_commented'?'commented':'updated the review'}
function relative(value:string,t:(source:string)=>string){const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));return days<1?t('Today'):days<7?`${days}d`:`${Math.floor(days/7)}w`}
function commandKeyDown(event:React.KeyboardEvent<HTMLElement>){if(event.key!=='ArrowDown'&&event.key!=='ArrowUp')return;event.preventDefault();const items=[...event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],[role=option]:not([aria-disabled=true])')].filter(item=>item.offsetParent!==null);if(!items.length)return;const current=items.indexOf(document.activeElement as HTMLElement),step=event.key==='ArrowDown'?1:-1;items[(current+step+items.length)%items.length]?.focus()}
